In [2]:
!pip install -q unsloth transformers datasets accelerate peft trl gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.0/56.0 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.4/67.4 MB 13.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 129.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 43.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 40.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 428.0/428.0 kB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 118.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 118.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 120.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 kB 23.6 MB/s eta 0:00:00

In [ ]:
# =========================================================
# CORE DEEP LEARNING LIBRARY
# =========================================================

import torch

# WHY TORCH:
# ---------------------------------------------------------
# PyTorch is the primary deep learning framework used for:
# - Tensor computations
# - GPU acceleration
# - Automatic differentiation (autograd)
# - Neural network training/inference
#
# WHY INDUSTRY USES IT:
# - Dynamic computation graph (easy debugging)
# - Strong ecosystem (Transformers, TRL, PEFT, etc.)
# - CUDA integration for GPU training
#
# IN THIS PROJECT:
# - Handles tensors during fine-tuning
# - Manages GPU execution
# - Powers model forward/backward passes
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Flexible and research-friendly
# + Excellent GPU support
# - Higher memory usage than lower-level frameworks



# =========================================================
# HUGGINGFACE DATASETS
# =========================================================

from datasets import load_dataset

# WHY THIS LIBRARY:
# ---------------------------------------------------------
# HuggingFace Datasets provides:
# - Efficient dataset loading
# - Streaming support
# - Dataset preprocessing
# - Standardized NLP pipelines
#
# WHY load_dataset():
# ---------------------------------------------------------
# Used to:
# - Download datasets from HuggingFace Hub
# - Load local datasets
# - Handle train/validation splits
#
# EXAMPLE:
# ---------------------------------------------------------
# dataset = load_dataset("imdb")
#
# BENEFITS:
# ---------------------------------------------------------
# + Memory-efficient Arrow backend
# + Fast tokenization pipelines
# + Built-in caching
#
# TRADE-OFF:
# ---------------------------------------------------------
# - Adds dependency complexity
# - Large datasets may still require streaming
#
# IMPORTANT:
# ---------------------------------------------------------
# Datasets are often lazily loaded and cached automatically.



# =========================================================
# UNSLOTH - OPTIMIZED LLM FINE-TUNING
# =========================================================

from unsloth import FastLanguageModel

# WHY UNSLOTH:
# ---------------------------------------------------------
# Unsloth is an optimized library for:
# - Faster LLM fine-tuning
# - Lower VRAM usage
# - LoRA/QLoRA acceleration
#
# WHAT FastLanguageModel DOES:
# ---------------------------------------------------------
# - Loads optimized Transformer models
# - Applies memory-efficient patches
# - Supports 4-bit quantization
#
# WHY IMPORTANT:
# ---------------------------------------------------------
# Standard LLM fine-tuning is extremely expensive.
#
# Example:
# - Normal Llama-7B training:
#     ~28GB+ VRAM
#
# - QLoRA + Unsloth:
#     ~8GB-12GB VRAM
#
# MAJOR OPTIMIZATIONS:
# ---------------------------------------------------------
# + Faster attention kernels
# + Quantized weights
# + Efficient gradient checkpointing
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Huge memory savings
# + Faster training
# - Slight precision loss (quantization)
#
# INDUSTRY IMPACT:
# ---------------------------------------------------------
# Makes consumer-GPU fine-tuning practical.



# =========================================================
# HUGGINGFACE TRAINING CONFIGURATION
# =========================================================

from transformers import TrainingArguments

# WHY TrainingArguments:
# ---------------------------------------------------------
# Centralized configuration system for training.
#
# CONTROLS:
# ---------------------------------------------------------
# - Batch size
# - Learning rate
# - Logging
# - Checkpointing
# - Evaluation strategy
# - Mixed precision
#
# WHY IMPORTANT:
# ---------------------------------------------------------
# Keeps training pipeline configurable and reproducible.
#
# EXAMPLE:
# ---------------------------------------------------------
# TrainingArguments(
#     output_dir="./results",
#     per_device_train_batch_size=4,
#     learning_rate=2e-5
# )
#
# DESIGN BENEFIT:
# ---------------------------------------------------------
# Separates:
# - Model architecture
# - Training strategy
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Cleaner experimentation
# - Large number of parameters can overwhelm beginners



# =========================================================
# TRL (TRANSFORMER REINFORCEMENT LEARNING)
# =========================================================

from trl import SFTTrainer

# WHY TRL:
# ---------------------------------------------------------
# TRL = Transformer Reinforcement Learning library.
#
# Built specifically for:
# - Supervised Fine-Tuning (SFT)
# - RLHF (Reinforcement Learning from Human Feedback)
# - Preference optimization
#
# WHY SFTTrainer:
# ---------------------------------------------------------
# Specialized trainer for instruction tuning LLMs.
#
# WHAT IT AUTOMATES:
# ---------------------------------------------------------
# - Tokenization
# - Dataset formatting
# - Loss calculation
# - Training loop
# - Evaluation
#
# WHY NOT USE BASIC Trainer:
# ---------------------------------------------------------
# SFTTrainer is optimized specifically for:
# - Conversational datasets
# - Prompt-response formatting
# - Chat templates
#
# INDUSTRY USAGE:
# ---------------------------------------------------------
# Used in:
# - Instruction tuning
# - ChatGPT-style assistant training
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Easier LLM fine-tuning
# + Handles conversational formatting
# - Less low-level control than custom training loops



# =========================================================
# GRADIO - WEB UI FOR MODELS
# =========================================================

import gradio as gr

# WHY GRADIO:
# ---------------------------------------------------------
# Gradio creates interactive web interfaces for ML models.
#
# WHAT IT ENABLES:
# ---------------------------------------------------------
# - Chat interfaces
# - Text generation demos
# - Model testing UIs
# - Public sharing
#
# EXAMPLE:
# ---------------------------------------------------------
# gr.Interface(fn=model_fn, inputs="text", outputs="text")
#
# WHY IMPORTANT:
# ---------------------------------------------------------
# Allows non-technical users to interact with models easily.
#
# INDUSTRY USAGE:
# ---------------------------------------------------------
# Common for:
# - AI demos
# - Internal testing tools
# - Research prototypes
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Extremely fast UI development
# + Beginner-friendly
# - Limited customization compared to React/frontend frameworks

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [ ]:
# =========================================================
# LOAD TEXT-TO-SQL DATASET
# =========================================================

dataset = load_dataset("gretelai/synthetic_text_to_sql")

# WHY THIS DATASET:
# ---------------------------------------------------------
# This dataset is designed for Text-to-SQL tasks.
#
# TASK:
# ---------------------------------------------------------
# Convert natural language → SQL query
#
# EXAMPLE:
# ---------------------------------------------------------
# Input:
#   "Show all employees earning above 50k"
#
# Output:
#   "SELECT * FROM employees WHERE salary > 50000"
#
# WHY IMPORTANT:
# ---------------------------------------------------------
# Text-to-SQL is a high-value enterprise AI task used in:
# - Business Intelligence tools
# - AI data assistants
# - Natural language database querying
# - Analytics copilots
#
# WHY "synthetic_text_to_sql":
# ---------------------------------------------------------
# Synthetic datasets:
# - Provide large-scale training examples
# - Cover many SQL patterns
# - Reduce expensive manual labeling
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Large scalable dataset
# + Good for bootstrapping models
# - Synthetic queries may lack real-world messiness
#
# WHAT load_dataset() DOES INTERNALLY:
# ---------------------------------------------------------
# - Downloads dataset from HuggingFace Hub
# - Caches locally
# - Loads Arrow-based memory-efficient dataset
#
# OUTPUT STRUCTURE:
# ---------------------------------------------------------
# dataset = {
#     "train": Dataset(...),
#     "test": Dataset(...)
# }
#
# MEMORY EFFICIENCY:
# ---------------------------------------------------------
# HuggingFace datasets use Apache Arrow backend:
# - Faster access
# - Lower memory overhead
# - Lazy loading support



# =========================================================
# TRAINING SUBSET
# =========================================================

train_data = dataset["train"].select(range(10000))

# WHY SELECT ONLY 10,000 SAMPLES:
# ---------------------------------------------------------
# Full datasets can be very large.
#
# Using subset:
# - Speeds up experimentation
# - Reduces GPU memory/time requirements
# - Helps debug pipeline quickly
#
# WHY range(10000):
# ---------------------------------------------------------
# Selects first 10k rows.
#
# NOTE:
# ---------------------------------------------------------
# This is deterministic selection.
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Faster iteration
# + Easier debugging
# - Reduced dataset diversity
# - Potential ordering bias
#
# BETTER APPROACH FOR REAL TRAINING:
# ---------------------------------------------------------
# Random sampling:
#
# train_data = dataset["train"].shuffle(seed=42).select(range(10000))
#
# WHY:
# - Prevents dataset ordering bias
#
# TIME COMPLEXITY:
# ---------------------------------------------------------
# O(k), where k = selected rows



# =========================================================
# VALIDATION SUBSET
# =========================================================

val_data = dataset["test"].select(range(1000))

# WHY VALIDATION DATA EXISTS:
# ---------------------------------------------------------
# Validation measures:
# - Generalization ability
# - Overfitting
# - Training progress
#
# WHY USE TEST SPLIT AS VALIDATION:
# ---------------------------------------------------------
# Common shortcut for experimentation.
#
# PRODUCTION BEST PRACTICE:
# ---------------------------------------------------------
# Separate:
# - Train
# - Validation
# - Test
#
# Example:
# ---------------------------------------------------------
# Train → learning
# Validation → hyperparameter tuning
# Test → final evaluation
#
# WHY ONLY 1000 SAMPLES:
# ---------------------------------------------------------
# Validation is expensive during training.
#
# Smaller validation:
# - Faster evaluation
# - Lower compute cost
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Faster iteration
# - Metrics may be noisier
#
# POTENTIAL ISSUE:
# ---------------------------------------------------------
# If test split is small:
# - Using only first 1000 may reduce coverage
#
# BETTER:
# ---------------------------------------------------------
# val_data = dataset["test"].shuffle(seed=42).select(range(1000))

In [ ]:
# =========================================================
# PROMPT FORMATTING FUNCTION
# =========================================================

def format_prompt(example):
    """
    Converts raw dataset rows into instruction-tuning format.

    WHY THIS FUNCTION EXISTS:
    ---------------------------------------------------------
    Large Language Models (LLMs) are trained on text sequences,
    not structured dictionaries.

    Raw dataset example:
    ---------------------------------------------------------
    {
        "sql_prompt": "...",
        "sql_context": "...",
        "sql": "SELECT ..."
    }

    MUST become:
    ---------------------------------------------------------
    A single formatted instruction-response string.

    WHY IMPORTANT:
    ---------------------------------------------------------
    Instruction tuning works best when prompts follow a
    consistent conversational structure.

    This teaches the model:
    - where the question starts
    - where context/schema appears
    - where the answer begins

    INDUSTRY CONCEPT:
    ---------------------------------------------------------
    This is called:
    - Prompt templating
    - Instruction formatting
    - Chat formatting

    SAME IDEA used in:
    - ChatGPT
    - Claude
    - Gemini
    - Llama instruction tuning
    """


    return {

        # =====================================================
        # FINAL TRAINING TEXT
        # =====================================================

        "text": f"""### Question:
{example['sql_prompt']}

### Schema:
{example['sql_context']}

### SQL:
{example['sql']}"""
    }


    # WHY RETURN DICTIONARY:
    # ---------------------------------------------------------
    # HuggingFace .map() expects transformed dataset rows.
    #
    # Returning:
    # {
    #   "text": formatted_string
    # }
    #
    # creates a new column named "text".
    #
    # WHY IMPORTANT:
    # ---------------------------------------------------------
    # SFTTrainer expects a single text field.
    #
    # Without this:
    # - Trainer cannot tokenize properly
    # - Dataset structure becomes incompatible



# =========================================================
# APPLY PROMPT FORMATTING TO TRAIN DATA
# =========================================================

train_data = train_data.map(format_prompt)

# WHAT .map() DOES:
# ---------------------------------------------------------
# Applies function to EVERY dataset row.
#
# PROCESS:
# ---------------------------------------------------------
# For each example:
#
# OLD:
# {
#   "sql_prompt": "...",
#   "sql_context": "...",
#   "sql": "..."
# }
#
# NEW:
# {
#   "text": "### Question: ..."
# }
#
# WHY MAP INSTEAD OF LOOP:
# ---------------------------------------------------------
# HuggingFace .map():
# - Optimized internally
# - Supports multiprocessing
# - Maintains dataset structure
# - Memory efficient
#
# TRADE-OFF:
# ---------------------------------------------------------
# + Fast and scalable
# + Cleaner preprocessing pipeline
# - Slight abstraction complexity
#
# TIME COMPLEXITY:
# ---------------------------------------------------------
# O(N), where N = number of dataset samples
#
# MEMORY NOTE:
# ---------------------------------------------------------
# Creates additional processed dataset columns.
#
# Large datasets may increase RAM usage.



# =========================================================
# APPLY SAME FORMAT TO VALIDATION DATA
# =========================================================

val_data = val_data.map(format_prompt)

# WHY SAME FORMAT MATTERS:
# ---------------------------------------------------------
# Validation distribution must match training distribution.
#
# If formatting differs:
# - Validation metrics become unreliable
# - Model may fail during inference
#
# CONSISTENCY IS CRITICAL:
# ---------------------------------------------------------
# LLMs are extremely sensitive to prompt structure.
#
# Example:
#
# TRAIN:
#   ### Question:
#
# INFERENCE:
#   User:
#
# → performance degradation possible
#
# INDUSTRY BEST PRACTICE:
# ---------------------------------------------------------
# Use same prompt template for:
# - training
# - validation
# - inference
#
# This is called:
# ---------------------------------------------------------
# "Prompt format alignment"

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [ ]:
# =========================================================
# LOAD PRETRAINED LLM + TOKENIZER
# =========================================================

model, tokenizer = FastLanguageModel.from_pretrained(

    # =====================================================
    # MODEL SELECTION
    # =====================================================

    model_name = "unsloth/llama-3-8b-bnb-4bit",

    # WHY THIS MODEL:
    # -----------------------------------------------------
    # This is a quantized version of Meta's Llama-3 8B model.
    #
    # BREAKDOWN:
    # -----------------------------------------------------
    # llama-3
    #   → Meta's modern LLM architecture
    #
    # 8b
    #   → ~8 billion parameters
    #
    # bnb
    #   → BitsAndBytes quantization backend
    #
    # 4bit
    #   → Weights compressed to 4-bit precision
    #
    # WHY CHOOSE 8B:
    # -----------------------------------------------------
    # 8B models are a strong balance:
    #
    # + Good reasoning capability
    # + Fits on consumer GPUs with quantization
    # + Much cheaper than 70B models
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + Smaller VRAM usage
    # + Faster inference/training
    # - Slightly weaker reasoning than larger models



    # =====================================================
    # MAXIMUM CONTEXT LENGTH
    # =====================================================

    max_seq_length = 2048,

    # WHY 2048:
    # -----------------------------------------------------
    # Defines maximum number of tokens model can process.
    #
    # EXAMPLE:
    # -----------------------------------------------------
    # Prompt + response combined must fit within 2048 tokens.
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Longer context:
    # + Better long-form reasoning
    # + More schema/context support
    #
    # BUT:
    # Attention complexity grows quadratically:
    #
    # O(T²)
    #
    # where T = sequence length
    #
    # MEMORY IMPACT:
    # -----------------------------------------------------
    # Doubling sequence length can drastically increase:
    # - VRAM usage
    # - computation time
    #
    # WHY 2048 IS COMMON:
    # -----------------------------------------------------
    # Good trade-off between:
    # - context capacity
    # - GPU efficiency
    #
    # PRODUCTION NOTE:
    # -----------------------------------------------------
    # Modern LLMs may support:
    # - 8k
    # - 32k
    # - 128k contexts
    #
    # But these require much more compute.



    # =====================================================
    # 4-BIT QUANTIZATION
    # =====================================================

    load_in_4bit = True,

    # WHY QUANTIZATION:
    # -----------------------------------------------------
    # Full precision models require enormous VRAM.
    #
    # Example:
    # -----------------------------------------------------
    # Llama-3 8B FP16:
    #   ~16GB+ VRAM
    #
    # Llama-3 8B 4-bit:
    #   ~5GB-6GB VRAM
    #
    # HUGE SAVINGS.
    #
    # WHAT 4-BIT MEANS:
    # -----------------------------------------------------
    # Weights stored using 4 bits instead of:
    #
    # FP32 → 32 bits
    # FP16 → 16 bits
    #
    # EFFECT:
    # -----------------------------------------------------
    # + Lower memory
    # + Faster loading
    # + Consumer GPU compatibility
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # - Slight numerical precision loss
    # - Tiny quality degradation possible
    #
    # WHY STILL WORKS WELL:
    # -----------------------------------------------------
    # LLM weights are highly redundant.
    #
    # Quantization preserves most semantic capability.
    #
    # INDUSTRY STANDARD:
    # -----------------------------------------------------
    # QLoRA training heavily relies on:
    # - 4-bit quantization
    # - LoRA adapters
    #
    # This enables efficient fine-tuning.
)


# =========================================================
# WHAT THIS FUNCTION RETURNS
# =========================================================

# model:
# ---------------------------------------------------------
# Quantized pretrained Transformer model
#
# tokenizer:
# ---------------------------------------------------------
# Matching tokenizer for the model vocabulary
#
# WHY TOKENIZER MUST MATCH MODEL:
# ---------------------------------------------------------
# Token IDs must align with embedding matrix.
#
# WRONG TOKENIZER:
# → corrupted inputs
# → nonsense outputs
#
# Example:
# ---------------------------------------------------------
# Token ID 123 in one tokenizer may represent:
#   "hello"
#
# But in another tokenizer:
#   "SELECT"
#
# Mismatch breaks model behavior completely.



# =========================================================
# WHAT HAPPENS INTERNALLY
# =========================================================

# FastLanguageModel.from_pretrained():
#
# 1. Downloads model weights
# 2. Loads tokenizer vocabulary
# 3. Applies quantization wrappers
# 4. Optimizes Transformer kernels
# 5. Configures device placement
#
# ADDITIONAL UNSLOTH OPTIMIZATIONS:
# ---------------------------------------------------------
# + Faster attention kernels
# + Efficient memory layout
# + Optimized LoRA support
# + Reduced VRAM fragmentation



# =========================================================
# WHY PRETRAINED MODELS MATTER
# =========================================================

# This model already knows:
# ---------------------------------------------------------
# - grammar
# - reasoning
# - coding
# - world knowledge
#
# Fine-tuning ONLY teaches:
# ---------------------------------------------------------
# - domain specialization
# - formatting behavior
# - task alignment
#
# THIS IS CRITICAL:
# ---------------------------------------------------------
# You are NOT training from scratch.
#
# Training 8B from scratch:
# ---------------------------------------------------------
# - millions of dollars
# - thousands of GPUs
# - enormous datasets
#
# Fine-tuning:
# ---------------------------------------------------------
# - affordable
# - practical
# - fast
#
# This is called:
# ---------------------------------------------------------
# Transfer Learning

==((====))==  Unsloth 2026.5.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/5.70G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/198 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

Unsloth: Will load unsloth/llama-3-8b-bnb-4bit as a legacy tokenizer.

In [ ]:
# =========================================================
# APPLY LoRA / PEFT ADAPTERS TO MODEL
# =========================================================

model = FastLanguageModel.get_peft_model(

    # =====================================================
    # BASE MODEL
    # =====================================================

    model,

    # WHY PASS THE MODEL:
    # -----------------------------------------------------
    # PEFT modifies the existing pretrained model by:
    # - freezing original weights
    # - injecting trainable adapter layers
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # The original LLM weights remain mostly unchanged.
    #
    # This dramatically reduces:
    # - VRAM usage
    # - training cost
    # - storage requirements



    # =====================================================
    # LoRA RANK
    # =====================================================

    r = 16,

    # WHAT "r" MEANS:
    # -----------------------------------------------------
    # LoRA approximates weight updates using
    # low-rank matrix decomposition.
    #
    # Instead of updating:
    #
    #   W ∈ R^(d x d)
    #
    # LoRA learns:
    #
    #   A ∈ R^(d x r)
    #   B ∈ R^(r x d)
    #
    # Final update:
    #
    #   ΔW = A × B
    #
    # WHY THIS WORKS:
    # -----------------------------------------------------
    # LLM fine-tuning updates often lie in a lower-dimensional
    # subspace.
    #
    # So:
    # - full weight updates are unnecessary
    #
    # WHY r = 16:
    # -----------------------------------------------------
    # Common balance between:
    # - quality
    # - memory efficiency
    #
    # SMALLER r:
    # -----------------------------------------------------
    # + Lower VRAM
    # + Faster training
    # - Lower adaptation capacity
    #
    # LARGER r:
    # -----------------------------------------------------
    # + Better learning capacity
    # - Higher memory + compute
    #
    # TYPICAL VALUES:
    # -----------------------------------------------------
    # r = 4   → tiny adaptation
    # r = 8   → lightweight tuning
    # r = 16  → balanced
    # r = 64+ → heavy specialization



    # =====================================================
    # TARGET MODULES
    # =====================================================

    target_modules = ["q_proj", "v_proj"],

    # WHAT THESE MODULES ARE:
    # -----------------------------------------------------
    # q_proj → Query projection
    # v_proj → Value projection
    #
    # These exist inside self-attention layers.
    #
    # ATTENTION PIPELINE:
    # -----------------------------------------------------
    # Input
    #   ↓
    # q_proj → Queries
    # k_proj → Keys
    # v_proj → Values
    #
    # WHY TARGET ONLY q_proj & v_proj:
    # -----------------------------------------------------
    # Research shows:
    # - attention projections are highly influential
    # - adapting them provides strong fine-tuning results
    #
    # WHY NOT ALL LAYERS:
    # -----------------------------------------------------
    # Full adaptation:
    # + better flexibility
    # - huge memory cost
    #
    # LoRA selectively adapts critical components.
    #
    # COMMON INDUSTRY CHOICE:
    # -----------------------------------------------------
    # ["q_proj", "v_proj"]
    #
    # SOMETIMES ALSO:
    # -----------------------------------------------------
    # ["q_proj", "k_proj", "v_proj", "o_proj"]
    #
    # MORE TARGETS:
    # -----------------------------------------------------
    # + More expressive fine-tuning
    # - Higher VRAM usage



    # =====================================================
    # LORA SCALING FACTOR
    # =====================================================

    lora_alpha = 16,

    # WHAT THIS DOES:
    # -----------------------------------------------------
    # Controls scaling of LoRA updates.
    #
    # Effective update:
    #
    #   scaled_update = (alpha / r) * (A × B)
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Prevents LoRA updates from:
    # - being too weak
    # - dominating pretrained knowledge
    #
    # WHY alpha = 16:
    # -----------------------------------------------------
    # Matches rank (r=16).
    #
    # COMMON HEURISTIC:
    # -----------------------------------------------------
    # alpha ≈ r
    #
    # EFFECT:
    # -----------------------------------------------------
    # Larger alpha:
    # + stronger adaptation
    # - higher overfitting risk
    #
    # Smaller alpha:
    # + safer updates
    # - weaker learning



    # =====================================================
    # LORA DROPOUT
    # =====================================================

    lora_dropout = 0.1,

    # WHY DROPOUT:
    # -----------------------------------------------------
    # Prevents overfitting during fine-tuning.
    #
    # HOW:
    # -----------------------------------------------------
    # Randomly disables some LoRA activations during training.
    #
    # WHY 0.1:
    # -----------------------------------------------------
    # Standard Transformer regularization value.
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # Higher dropout:
    # + better generalization
    # - slower convergence
    #
    # Lower dropout:
    # + faster fitting
    # - more overfitting risk
)



# =========================================================
# WHAT HAPPENS INTERNALLY
# =========================================================

# FastLanguageModel.get_peft_model():
#
# 1. Freezes most original weights
# 2. Inserts LoRA adapter matrices
# 3. Marks ONLY adapter params trainable
# 4. Configures efficient forward pass
#
# RESULT:
# ---------------------------------------------------------
# Original model:
#   mostly frozen
#
# New trainable parameters:
#   tiny LoRA adapters
#
# HUGE MEMORY SAVINGS:
# ---------------------------------------------------------
# Full fine-tuning:
#   train ALL parameters
#
# LoRA:
#   train tiny subset only



# =========================================================
# WHY PEFT MATTERS
# =========================================================

# PEFT = Parameter Efficient Fine-Tuning
#
# BEFORE PEFT:
# ---------------------------------------------------------
# Fine-tuning 8B model:
# - enormous VRAM
# - huge checkpoint files
# - expensive training
#
# AFTER PEFT:
# ---------------------------------------------------------
# + Much lower VRAM
# + Faster training
# + Tiny adapter files
# + Easier deployment
#
# Example:
# ---------------------------------------------------------
# Full model:
#   ~16GB+
#
# LoRA adapters:
#   ~100MB-500MB
#
# MASSIVE DIFFERENCE.



# =========================================================
# WHY THIS IS REVOLUTIONARY
# =========================================================

# LoRA changed the LLM ecosystem because:
#
# BEFORE:
# ---------------------------------------------------------
# Only large companies could fine-tune LLMs.
#
# AFTER:
# ---------------------------------------------------------
# Individuals with consumer GPUs can:
# - specialize models
# - build assistants
# - create domain experts
#
# This democratized LLM development.

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.1.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
Unsloth 2026.5.2 patched 32 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

In [ ]:
# =========================================================
# TRAINING CONFIGURATION FOR LLM FINE-TUNING
# =========================================================

training_args = TrainingArguments(

    # =====================================================
    # OUTPUT DIRECTORY
    # =====================================================

    output_dir="./sql-model",

    # WHY THIS EXISTS:
    # -----------------------------------------------------
    # Defines where training artifacts are stored.
    #
    # SAVED ITEMS:
    # -----------------------------------------------------
    # - model checkpoints
    # - optimizer states
    # - trainer logs
    # - configuration files
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Allows:
    # - resuming training
    # - evaluation
    # - deployment
    #
    # BEST PRACTICE:
    # -----------------------------------------------------
    # Use descriptive names:
    #
    # "./llama3-sql-assistant-v1"
    #
    # instead of generic folders.
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # More checkpoints → more disk usage



    # =====================================================
    # BATCH SIZE PER GPU
    # =====================================================

    per_device_train_batch_size=2,

    # WHAT THIS MEANS:
    # -----------------------------------------------------
    # Number of training samples processed simultaneously
    # on EACH GPU.
    #
    # WHY ONLY 2:
    # -----------------------------------------------------
    # LLMs are extremely memory intensive.
    #
    # Especially:
    # - 8B model
    # - 2048 sequence length
    # - attention activations
    #
    # Even with:
    # - 4-bit quantization
    # - LoRA
    #
    # VRAM is still heavily used.
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # Small batch:
    # + fits consumer GPUs
    # - noisier gradient updates
    #
    # Larger batch:
    # + smoother optimization
    # - much higher VRAM usage
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # Effective batch size is increased later using
    # gradient accumulation.



    # =====================================================
    # GRADIENT ACCUMULATION
    # =====================================================

    gradient_accumulation_steps=4,

    # WHY THIS EXISTS:
    # -----------------------------------------------------
    # Simulates larger batch sizes without increasing VRAM.
    #
    # PROCESS:
    # -----------------------------------------------------
    # Instead of:
    # - updating weights every batch
    #
    # It:
    # - accumulates gradients over 4 batches
    # - performs optimizer step once
    #
    # EFFECTIVE BATCH SIZE:
    # -----------------------------------------------------
    # effective_batch =
    # per_device_train_batch_size
    # × gradient_accumulation_steps
    #
    # HERE:
    # -----------------------------------------------------
    # 2 × 4 = 8 effective samples
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Larger effective batches often:
    # - stabilize training
    # - improve convergence
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + lower VRAM
    # + better gradient estimation
    # - slower wall-clock training
    #
    # INDUSTRY USAGE:
    # -----------------------------------------------------
    # Extremely common for LLM fine-tuning.



    # =====================================================
    # LEARNING RATE
    # =====================================================

    learning_rate=2e-4,

    # WHY THIS VALUE:
    # -----------------------------------------------------
    # Fine-tuning LLMs typically requires:
    # - smaller learning rates
    #
    # WHY:
    # -----------------------------------------------------
    # Pretrained models already contain useful knowledge.
    #
    # Too high LR:
    # -----------------------------------------------------
    # - destroys pretrained knowledge
    # - unstable training
    # - catastrophic forgetting
    #
    # Too low LR:
    # -----------------------------------------------------
    # - very slow adaptation
    #
    # WHY 2e-4:
    # -----------------------------------------------------
    # Common LoRA fine-tuning value.
    #
    # NOTE:
    # -----------------------------------------------------
    # LoRA often tolerates slightly higher learning rates
    # than full fine-tuning because:
    # - only adapter layers are trained.
    #
    # TYPICAL RANGES:
    # -----------------------------------------------------
    # Full fine-tuning:
    #   1e-5 → 5e-5
    #
    # LoRA:
    #   1e-4 → 3e-4



    # =====================================================
    # NUMBER OF EPOCHS
    # =====================================================

    num_train_epochs=1,

    # WHAT AN EPOCH MEANS:
    # -----------------------------------------------------
    # One full pass through training dataset.
    #
    # WHY ONLY 1:
    # -----------------------------------------------------
    # LLM fine-tuning datasets can be large.
    #
    # Often:
    # - few epochs are sufficient
    # - overfitting occurs quickly
    #
    # FOR EXPERIMENTATION:
    # -----------------------------------------------------
    # 1 epoch:
    # + fast testing
    # + quick debugging
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + faster iteration
    # - possibly undertrained
    #
    # PRODUCTION:
    # -----------------------------------------------------
    # Usually monitored with:
    # - validation loss
    # - early stopping
    #
    # rather than fixed epochs.



    # =====================================================
    # LOGGING FREQUENCY
    # =====================================================

    logging_steps=20,

    # WHY LOGGING EXISTS:
    # -----------------------------------------------------
    # Tracks training progress.
    #
    # TYPICALLY LOGS:
    # -----------------------------------------------------
    # - loss
    # - learning rate
    # - gradient norms
    #
    # WHY 20:
    # -----------------------------------------------------
    # Balance between:
    # - visibility
    # - overhead
    #
    # TOO FREQUENT:
    # -----------------------------------------------------
    # + detailed monitoring
    # - slower training
    #
    # TOO INFREQUENT:
    # -----------------------------------------------------
    # + faster training
    # - hard to debug
    #
    # INDUSTRY:
    # -----------------------------------------------------
    # Usually integrated with:
    # - TensorBoard
    # - Weights & Biases
    # - MLflow



    # =====================================================
    # FP16 MIXED PRECISION
    # =====================================================

    fp16=True,

    # WHAT FP16 DOES:
    # -----------------------------------------------------
    # Uses half-precision floating point numbers.
    #
    # STANDARD:
    # -----------------------------------------------------
    # FP32 → 32-bit precision
    #
    # FP16:
    # -----------------------------------------------------
    # - half memory usage
    # - faster tensor operations
    #
    # WHY IMPORTANT FOR LLMS:
    # -----------------------------------------------------
    # LLMs are extremely memory heavy.
    #
    # FP16 enables:
    # - larger models
    # - larger batch sizes
    # - faster training
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + major VRAM savings
    # + faster training
    # - possible numerical instability
    #
    # WHY IT STILL WORKS:
    # -----------------------------------------------------
    # Modern GPUs:
    # - Tensor Cores
    # - AMP scaling
    #
    # help stabilize FP16 training.
    #
    # MODERN ALTERNATIVE:
    # -----------------------------------------------------
    # bf16=True
    #
    # Often more stable on newer GPUs.
)

In [ ]:
# =========================================================
# CREATE SUPERVISED FINE-TUNING TRAINER
# =========================================================

trainer = SFTTrainer(

    # =====================================================
    # MODEL TO TRAIN
    # =====================================================

    model=model,

    # WHY THIS PARAMETER EXISTS:
    # -----------------------------------------------------
    # Specifies which neural network will be fine-tuned.
    #
    # HERE:
    # -----------------------------------------------------
    # This is:
    # - Llama-3 8B
    # - quantized to 4-bit
    # - enhanced with LoRA adapters
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # The model already contains pretrained language
    # knowledge.
    #
    # Fine-tuning ONLY teaches:
    # - SQL generation behavior
    # - formatting alignment
    # - domain specialization
    #
    # WHY PASS MODEL INTO TRAINER:
    # -----------------------------------------------------
    # Trainer needs:
    # - forward pass access
    # - gradient computation
    # - optimizer integration
    # - checkpoint saving
    #
    # WITHOUT THIS:
    # -----------------------------------------------------
    # Trainer would have nothing to optimize.



    # =====================================================
    # TRAINING DATASET
    # =====================================================

    train_dataset=train_data,

    # WHY THIS DATASET EXISTS:
    # -----------------------------------------------------
    # Contains examples the model learns from.
    #
    # EACH SAMPLE:
    # -----------------------------------------------------
    # Question
    # + Database schema
    # + Correct SQL answer
    #
    # PURPOSE:
    # -----------------------------------------------------
    # Teach model mapping:
    #
    # Natural language
    #          ↓
    # SQL query generation
    #
    # WHY TRAIN DATA IS CRITICAL:
    # -----------------------------------------------------
    # Model quality heavily depends on:
    # - dataset quality
    # - formatting consistency
    # - diversity
    #
    # GARBAGE DATA:
    # -----------------------------------------------------
    # → garbage model outputs
    #
    # This is known as:
    # -----------------------------------------------------
    # "Garbage In, Garbage Out"



    # =====================================================
    # VALIDATION DATASET
    # =====================================================

    eval_dataset=val_data,

    # WHY VALIDATION EXISTS:
    # -----------------------------------------------------
    # Measures model performance during training.
    #
    # PURPOSE:
    # -----------------------------------------------------
    # Detect:
    # - overfitting
    # - underfitting
    # - unstable training
    #
    # TRAIN VS VALIDATION:
    # -----------------------------------------------------
    # Train:
    #   model learns
    #
    # Validation:
    #   model is tested on unseen examples
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # A model memorizing train data is NOT useful.
    #
    # Validation estimates:
    # - real-world generalization ability
    #
    # WITHOUT VALIDATION:
    # -----------------------------------------------------
    # You may unknowingly:
    # - overfit badly
    # - destroy pretrained behavior



    # =====================================================
    # TEXT FIELD NAME
    # =====================================================

    dataset_text_field="text",

    # WHY THIS PARAMETER EXISTS:
    # -----------------------------------------------------
    # SFTTrainer needs to know:
    # which dataset column contains final training text.
    #
    # YOUR PREPROCESSING CREATED:
    # -----------------------------------------------------
    # {
    #   "text": "### Question: ..."
    # }
    #
    # Trainer uses this field for:
    # -----------------------------------------------------
    # - tokenization
    # - sequence packing
    # - loss computation
    #
    # WITHOUT THIS:
    # -----------------------------------------------------
    # Trainer would not know:
    # - which field to tokenize
    #
    # RESULT:
    # -----------------------------------------------------
    # Runtime error or incorrect training.
    #
    # WHY "text" IS COMMON:
    # -----------------------------------------------------
    # Standard convention in instruction tuning pipelines.



    # =====================================================
    # MAXIMUM SEQUENCE LENGTH
    # =====================================================

    max_seq_length=2048,

    # WHAT THIS CONTROLS:
    # -----------------------------------------------------
    # Maximum number of tokens processed per sample.
    #
    # INCLUDES:
    # -----------------------------------------------------
    # - question
    # - schema
    # - SQL answer
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Transformer attention cost scales quadratically:
    #
    # O(T²)
    #
    # where:
    # T = sequence length
    #
    # LONGER SEQUENCES:
    # -----------------------------------------------------
    # + better long-context reasoning
    # - much higher VRAM usage
    # - slower training
    #
    # WHY 2048:
    # -----------------------------------------------------
    # Common balance:
    # - enough room for schemas
    # - manageable GPU memory
    #
    # WHAT HAPPENS IF EXCEEDED:
    # -----------------------------------------------------
    # Text is truncated.
    #
    # RISK:
    # -----------------------------------------------------
    # Important schema info may be lost.
    #
    # PRODUCTION SYSTEMS:
    # -----------------------------------------------------
    # Often use:
    # - schema compression
    # - retrieval systems
    # - chunking



    # =====================================================
    # TOKENIZER
    # =====================================================

    tokenizer=tokenizer,

    # WHY TOKENIZER IS REQUIRED:
    # -----------------------------------------------------
    # LLMs cannot process raw text directly.
    #
    # Text must become:
    # -----------------------------------------------------
    # token IDs
    #
    # EXAMPLE:
    # -----------------------------------------------------
    # "SELECT * FROM users"
    #
    # →
    #
    # [1234, 88, 912, ...]
    #
    # WHY TOKENIZER MUST MATCH MODEL:
    # -----------------------------------------------------
    # Embedding matrix expects specific token IDs.
    #
    # WRONG TOKENIZER:
    # -----------------------------------------------------
    # → corrupted semantics
    # → nonsensical outputs
    #
    # TOKENIZER RESPONSIBILITIES:
    # -----------------------------------------------------
    # - tokenization
    # - truncation
    # - padding
    # - special tokens
    #
    # INDUSTRY NOTE:
    # -----------------------------------------------------
    # Tokenization quality heavily impacts:
    # - training efficiency
    # - inference quality



    # =====================================================
    # TRAINING CONFIGURATION
    # =====================================================

    args=training_args,

    # WHY THIS EXISTS:
    # -----------------------------------------------------
    # Contains:
    # - learning rate
    # - batch size
    # - fp16 settings
    # - logging configuration
    # - checkpoint behavior
    #
    # BENEFIT:
    # -----------------------------------------------------
    # Separates:
    # - training logic
    # - training configuration
    #
    # This improves:
    # -----------------------------------------------------
    # - maintainability
    # - experimentation
    # - reproducibility
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/10000 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/1000 [00:00<?, ? examples/s]

In [ ]:
trainer.train()
trainer.save_model("sql-model")

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 1 | Total steps = 1,250
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 6,815,744 of 8,037,076,992 (0.08% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Restored added_tokens_decoder metadata in ./sql-model/checkpoint-500/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in ./sql-model/checkpoint-1000/tokenizer_config.json.

Unsloth: Restored added_tokens_decoder metadata in ./sql-model/checkpoint-1250/tokenizer_config.json.
Unsloth: Restored added_tokens_decoder metadata in sql-model/tokenizer_config.json.

In [ ]:
# =========================================================
# SQL GENERATION FUNCTION
# =========================================================

def generate_sql(question, schema):

    """
    Generates SQL queries using the fine-tuned LLM.

    PURPOSE:
    ---------------------------------------------------------
    Converts:
        Natural language + database schema
    into:
        SQL query

    WHY THIS FUNCTION EXISTS:
    ---------------------------------------------------------
    During training:
    - model learns mappings from prompts → SQL

    During inference:
    - this function performs actual prediction/generation

    This is the real deployment-time interface.

    INDUSTRY USE CASE:
    ---------------------------------------------------------
    This exact architecture powers:
    - AI SQL copilots
    - BI assistants
    - analytics chatbots
    - natural language querying systems
    """



    # =====================================================
    # PROMPT TEMPLATE
    # =====================================================

    prompt = f"""### Question:
{question}

### Schema:
{schema}

### SQL:"""

    # WHY PROMPT TEMPLATE MATTERS:
    # -----------------------------------------------------
    # LLMs are highly sensitive to formatting.
    #
    # During training:
    # -----------------------------------------------------
    # The model learned this exact structure:
    #
    # ### Question:
    # ...
    #
    # ### Schema:
    # ...
    #
    # ### SQL:
    #
    # Therefore inference MUST match training format.
    #
    # This concept is called:
    # -----------------------------------------------------
    # Prompt format alignment
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Different formatting can:
    # - reduce performance
    # - confuse generation
    # - decrease SQL accuracy
    #
    # WHY SECTION HEADERS HELP:
    # -----------------------------------------------------
    # They act as semantic delimiters.
    #
    # Model learns:
    # -----------------------------------------------------
    # "Question section"
    # "Schema section"
    # "Answer section"
    #
    # WITHOUT STRUCTURE:
    # -----------------------------------------------------
    # The model has weaker contextual separation.
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + Better clarity
    # + Better instruction following
    # - Slightly more tokens consumed



    # =====================================================
    # TOKENIZATION
    # =====================================================

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    # WHY TOKENIZATION IS REQUIRED:
    # -----------------------------------------------------
    # Neural networks cannot process raw text.
    #
    # Text must become:
    # -----------------------------------------------------
    # numerical token IDs
    #
    # Example:
    # -----------------------------------------------------
    # "SELECT * FROM users"
    #
    # →
    #
    # [1234, 88, 912, ...]
    #
    # WHAT return_tensors="pt" DOES:
    # -----------------------------------------------------
    # Converts output into PyTorch tensors.
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Model expects tensor inputs.
    #
    # WITHOUT THIS:
    # -----------------------------------------------------
    # Tokenizer returns Python lists instead.
    #
    # WHY .to("cuda"):
    # -----------------------------------------------------
    # Moves tensors onto GPU memory.
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # Model and tensors MUST be on same device.
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # Runtime error:
    #
    # "Expected all tensors to be on same device"
    #
    # WHY GPU MATTERS:
    # -----------------------------------------------------
    # LLM inference is computationally expensive.
    #
    # GPU provides:
    # -----------------------------------------------------
    # + massively parallel computation
    # + much faster matrix multiplication
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + fast inference
    # - requires CUDA-compatible hardware
    #
    # PRODUCTION NOTE:
    # -----------------------------------------------------
    # Better:
    #
    # .to(model.device)
    #
    # instead of hardcoding "cuda"



    # =====================================================
    # TEXT GENERATION
    # =====================================================

    outputs = model.generate(

        # -------------------------------------------------
        # EXPAND TOKENIZED INPUTS
        # -------------------------------------------------

        **inputs,

        # WHY **inputs:
        # -------------------------------------------------
        # Expands dictionary into keyword arguments.
        #
        # Example:
        # -------------------------------------------------
        # {
        #   "input_ids": ...,
        #   "attention_mask": ...
        # }
        #
        # becomes:
        #
        # input_ids=...
        # attention_mask=...
        #
        # WHY IMPORTANT:
        # -------------------------------------------------
        # generate() expects named tensor arguments.



        # -------------------------------------------------
        # MAXIMUM GENERATED TOKENS
        # -------------------------------------------------

        max_new_tokens=100,

        # WHAT THIS CONTROLS:
        # -------------------------------------------------
        # Limits number of generated output tokens.
        #
        # WHY IMPORTANT:
        # -------------------------------------------------
        # Prevents:
        # - runaway generation
        # - infinite outputs
        # - huge latency
        #
        # WHY 100:
        # -------------------------------------------------
        # SQL queries are usually short-medium length.
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Smaller values:
        # + faster inference
        # - possible truncation
        #
        # Larger values:
        # + more complete outputs
        # - slower inference
        # - higher hallucination risk
        #
        # IMPORTANT:
        # -------------------------------------------------
        # Generation cost scales with token count.



        # -------------------------------------------------
        # TEMPERATURE SAMPLING
        # -------------------------------------------------

        temperature=0.2,

        # WHAT TEMPERATURE DOES:
        # -------------------------------------------------
        # Controls randomness during token sampling.
        #
        # LOWER TEMPERATURE:
        # -------------------------------------------------
        # More deterministic
        # More confident outputs
        #
        # HIGHER TEMPERATURE:
        # -------------------------------------------------
        # More creative/random outputs
        #
        # WHY LOW TEMPERATURE FOR SQL:
        # -------------------------------------------------
        # SQL generation requires:
        # - precision
        # - consistency
        # - correctness
        #
        # Creativity is BAD here.
        #
        # WHY 0.2:
        # -------------------------------------------------
        # Common low-randomness value for:
        # - coding
        # - SQL
        # - structured generation
        #
        # TYPICAL RANGES:
        # -------------------------------------------------
        # 0.0 → deterministic
        # 0.2 → stable
        # 0.7 → balanced creativity
        # 1.0+ → highly random
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Lower temp:
        # + reliable outputs
        # - less diversity
        #
        # Higher temp:
        # + more exploration
        # - more hallucinations
    )



    # =====================================================
    # DECODE GENERATED TOKENS
    # =====================================================

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

    # WHAT decode() DOES:
    # -----------------------------------------------------
    # Converts token IDs back into human-readable text.
    #
    # Example:
    # -----------------------------------------------------
    # [1234, 88, 912]
    #
    # →
    #
    # "SELECT * FROM users"
    #
    # WHY outputs[0]:
    # -----------------------------------------------------
    # generate() returns batch output.
    #
    # Shape:
    # -----------------------------------------------------
    # [batch_size, sequence_length]
    #
    # outputs[0]:
    # -----------------------------------------------------
    # selects first generated sequence.
    #
    # WHY skip_special_tokens=True:
    # -----------------------------------------------------
    # Removes tokens like:
    # - <bos>
    # - <eos>
    # - <pad>
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Cleaner final output for users.
    #
    # WITHOUT THIS:
    # -----------------------------------------------------
    # Generated text may contain model control tokens.

In [ ]:
# =========================================================
# PREDICTION WRAPPER FUNCTION
# =========================================================

def predict(q, s):

    """
    Wrapper function for Gradio UI inference.

    PURPOSE:
    ---------------------------------------------------------
    Connects frontend user inputs to backend LLM generation.

    INPUTS:
    ---------------------------------------------------------
    q → natural language question
    s → database schema/context

    OUTPUT:
    ---------------------------------------------------------
    Generated SQL query text

    WHY THIS FUNCTION EXISTS:
    ---------------------------------------------------------
    Gradio expects a callable function:
    - takes UI inputs
    - returns UI outputs

    This wrapper acts as the bridge between:
    ---------------------------------------------------------
    Frontend UI
            ↓
    LLM inference pipeline

    WHY NOT CALL generate_sql DIRECTLY:
    ---------------------------------------------------------
    Separation of concerns.

    BENEFITS:
    ---------------------------------------------------------
    + cleaner architecture
    + easier debugging
    + easier future extension
    + allows preprocessing/postprocessing later

    FUTURE IMPROVEMENTS:
    ---------------------------------------------------------
    You could later add:
    - input validation
    - schema sanitization
    - SQL cleanup
    - logging
    - authentication
    - caching
    """

    return generate_sql(q, s)

    # WHY RETURN DIRECTLY:
    # -----------------------------------------------------
    # Current wrapper performs pure pass-through behavior.
    #
    # SIMPLE FLOW:
    # -----------------------------------------------------
    # UI Input
    #     ↓
    # predict()
    #     ↓
    # generate_sql()
    #     ↓
    # generated SQL returned to UI
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + minimal abstraction
    # + easy readability
    # - limited processing control
    #
    # PRODUCTION:
    # -----------------------------------------------------
    # Usually additional layers are inserted:
    # - validation
    # - moderation
    # - telemetry
    # - retry logic



# =========================================================
# CREATE GRADIO WEB INTERFACE
# =========================================================

demo = gr.Interface(

    # =====================================================
    # BACKEND FUNCTION
    # =====================================================

    fn=predict,

    # WHY fn EXISTS:
    # -----------------------------------------------------
    # Defines which Python function Gradio should call
    # whenever user submits input.
    #
    # FLOW:
    # -----------------------------------------------------
    # User enters data
    #     ↓
    # Gradio calls:
    # predict(q, s)
    #     ↓
    # Function returns output
    #     ↓
    # UI displays result
    #
    # THIS IS EVENT-DRIVEN EXECUTION.



    # =====================================================
    # INPUT COMPONENTS
    # =====================================================

    inputs=[

        # -------------------------------------------------
        # QUESTION INPUT BOX
        # -------------------------------------------------

        gr.Textbox(label="Question"),

        # WHY TEXTBOX:
        # -------------------------------------------------
        # User needs free-form natural language input.
        #
        # Example:
        # -------------------------------------------------
        # "Show all employees with salary > 50000"
        #
        # WHY LABEL:
        # -------------------------------------------------
        # Improves UX clarity.
        #
        # WITHOUT LABEL:
        # -------------------------------------------------
        # Users may not understand expected input.
        #
        # INDUSTRY NOTE:
        # -------------------------------------------------
        # UI clarity strongly impacts usability.



        # -------------------------------------------------
        # SCHEMA INPUT BOX
        # -------------------------------------------------

        gr.Textbox(label="Schema"),

        # WHY SEPARATE SCHEMA FIELD:
        # -------------------------------------------------
        # SQL generation depends heavily on:
        # - table names
        # - column names
        # - relationships
        #
        # EXAMPLE:
        # -------------------------------------------------
        # CREATE TABLE employees (
        #     id INT,
        #     salary INT
        # )
        #
        # WHY IMPORTANT:
        # -------------------------------------------------
        # LLM needs grounding information.
        #
        # OTHERWISE:
        # -------------------------------------------------
        # Model may hallucinate:
        # - tables
        # - columns
        # - relationships
        #
        # THIS IS CALLED:
        # -------------------------------------------------
        # Schema grounding
    ],



    # =====================================================
    # OUTPUT COMPONENT
    # =====================================================

    outputs=gr.Textbox(label="SQL"),

    # WHY OUTPUT TEXTBOX:
    # -----------------------------------------------------
    # SQL generation produces text output.
    #
    # Example:
    # -----------------------------------------------------
    # SELECT * FROM employees
    # WHERE salary > 50000;
    #
    # WHY LABEL OUTPUT:
    # -----------------------------------------------------
    # Improves readability and UX.
    #
    # INDUSTRY NOTE:
    # -----------------------------------------------------
    # Even simple UI labeling improves:
    # - user trust
    # - usability
    # - accessibility
)



# =========================================================
# START WEB SERVER
# =========================================================

demo.launch()

# WHAT launch() DOES:
# ---------------------------------------------------------
# Starts local web server hosting the UI.
#
# INTERNALLY:
# ---------------------------------------------------------
# 1. Creates backend API routes
# 2. Starts frontend server
# 3. Opens browser interface
# 4. Handles user requests
#
# RESULT:
# ---------------------------------------------------------
# Interactive AI web app.
#
# USER FLOW:
# ---------------------------------------------------------
# Browser
#   ↓
# User enters question/schema
#   ↓
# Gradio sends request to backend
#   ↓
# predict()
#   ↓
# generate_sql()
#   ↓
# Model inference
#   ↓
# SQL returned to browser
#
# WHY THIS IS POWERFUL:
# ---------------------------------------------------------
# Converts ML model into usable product instantly.
#
# WITHOUT GRADIO:
# ---------------------------------------------------------
# You would manually build:
# - frontend
# - backend API
# - request handling
# - serialization
# - deployment pipeline
#
# Gradio dramatically simplifies prototyping.
#
# TRADE-OFF:
# ---------------------------------------------------------
# + extremely fast development
# + minimal code
# + beginner-friendly
# - less customizable than full web frameworks
#
# PRODUCTION LIMITATION:
# ---------------------------------------------------------
# Large-scale systems usually migrate to:
# - FastAPI
# - React
# - Kubernetes
# - dedicated inference servers
#
# because Gradio is best for:
# ---------------------------------------------------------
# - demos
# - prototypes
# - research tools
# - internal apps

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://565df5087be992e412.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
# =========================================================
# SQLITE DATABASE LIBRARY
# =========================================================

import sqlite3

# WHY SQLITE3:
# ---------------------------------------------------------
# sqlite3 is Python's built-in lightweight relational
# database engine.
#
# WHY IMPORTANT HERE:
# ---------------------------------------------------------
# This project generates SQL using an LLM.
#
# Generated SQL must be:
# - validated
# - executed
# - tested
#
# sqlite3 provides a safe local SQL execution environment.
#
# WHY SQLITE IS IDEAL FOR THIS:
# ---------------------------------------------------------
# + zero external setup
# + embedded database
# + fast for small workloads
# + perfect for experimentation
#
# NO DATABASE SERVER REQUIRED.
#
# INDUSTRY USE CASES:
# ---------------------------------------------------------
# SQLite is commonly used for:
# - local apps
# - testing
# - prototyping
# - mobile apps
# - browser databases
#
# TRADE-OFF:
# ---------------------------------------------------------
# + lightweight
# + portable
# - not ideal for massive concurrent systems
#
# IMPORTANT:
# ---------------------------------------------------------
# This code creates an in-memory database, meaning:
# - database exists temporarily
# - destroyed after execution
#
# This improves:
# ---------------------------------------------------------
# + safety
# + isolation
# + repeatability



# =========================================================
# SQL EXECUTION FUNCTION
# =========================================================

def execute_sql(schema_sql, query):

    """
    Executes generated SQL inside temporary SQLite database.

    PURPOSE:
    ---------------------------------------------------------
    Validates whether generated SQL:
    - is syntactically correct
    - executes successfully
    - produces results

    INPUTS:
    ---------------------------------------------------------
    schema_sql:
        SQL schema definition
        (CREATE TABLE statements)

    query:
        SQL query generated by LLM

    OUTPUT:
    ---------------------------------------------------------
    (success, result)

    success:
        True/False execution status

    result:
        query result OR error message

    WHY THIS FUNCTION IS IMPORTANT:
    ---------------------------------------------------------
    LLM-generated SQL may:
    - contain syntax errors
    - reference missing columns
    - hallucinate tables
    - produce invalid queries

    This function acts as:
    ---------------------------------------------------------
    SQL verification layer
    """



    # =====================================================
    # CREATE TEMPORARY IN-MEMORY DATABASE
    # =====================================================

    conn = sqlite3.connect(":memory:")

    # WHY ":memory:":
    # -----------------------------------------------------
    # Creates temporary RAM-based database.
    #
    # BENEFITS:
    # -----------------------------------------------------
    # + extremely fast
    # + isolated execution
    # + automatically cleaned up
    # + safer experimentation
    #
    # WHY NOT FILE DATABASE:
    # -----------------------------------------------------
    # File DB:
    # - persists data
    # - slower disk IO
    # - risk of corruption/modification
    #
    # MEMORY DB IS IDEAL FOR:
    # -----------------------------------------------------
    # - testing
    # - evaluation
    # - temporary execution
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # Database disappears after connection closes.
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + speed
    # + safety
    # - non-persistent



    # =====================================================
    # CREATE DATABASE CURSOR
    # =====================================================

    cursor = conn.cursor()

    # WHAT A CURSOR IS:
    # -----------------------------------------------------
    # Cursor acts as command interface to database.
    #
    # RESPONSIBILITIES:
    # -----------------------------------------------------
    # - execute SQL
    # - fetch results
    # - navigate query outputs
    #
    # WHY SEPARATE CURSOR EXISTS:
    # -----------------------------------------------------
    # Database connection:
    #   manages session
    #
    # Cursor:
    #   performs operations
    #
    # THIS IS STANDARD DB API DESIGN.



    # =====================================================
    # ERROR HANDLING BLOCK
    # =====================================================

    try:

        # WHY TRY/EXCEPT EXISTS:
        # -------------------------------------------------
        # SQL generation is unreliable by nature.
        #
        # LLM outputs may contain:
        # - syntax errors
        # - invalid columns
        # - malformed queries
        #
        # Without try/except:
        # -------------------------------------------------
        # application crashes completely.
        #
        # This improves:
        # -------------------------------------------------
        # + robustness
        # + user experience
        # + debugging capability



        # =================================================
        # CREATE DATABASE SCHEMA
        # =================================================

        for stmt in schema_sql.split(";"):

            # WHY split(";"):
            # ---------------------------------------------
            # Schema may contain multiple SQL statements.
            #
            # Example:
            # -------------------------------------------------
            # CREATE TABLE users (...);
            # CREATE TABLE orders (...);
            #
            # split(";") separates statements individually.
            #
            # WHY IMPORTANT:
            # -------------------------------------------------
            # SQLite cursor.execute() usually handles one
            # statement at a time.
            #
            # TRADE-OFF:
            # -------------------------------------------------
            # + simple parsing
            # - naive splitting
            #
            # POTENTIAL ISSUE:
            # -------------------------------------------------
            # Semicolons inside strings/comments may break logic.
            #
            # PRODUCTION:
            # -------------------------------------------------
            # Real parsers use SQL AST/tokenizers.



            if stmt.strip():

                # WHY strip():
                # ---------------------------------------------
                # Removes whitespace/newlines.
                #
                # WHY IMPORTANT:
                # -------------------------------------------------
                # split(";") may create empty strings:
                #
                # ["CREATE TABLE...", "", ""]
                #
                # Empty execution would raise errors.
                #
                # CONDITIONAL PREVENTS:
                # -------------------------------------------------
                # executing blank SQL statements.



                cursor.execute(stmt)

                # WHAT execute() DOES:
                # ---------------------------------------------
                # Sends SQL command to SQLite engine.
                #
                # HERE:
                # -------------------------------------------------
                # Creates database tables/schema.
                #
                # EXAMPLE:
                # -------------------------------------------------
                # CREATE TABLE employees (
                #   id INT,
                #   salary INT
                # )
                #
                # WHY SCHEMA CREATION FIRST:
                # -------------------------------------------------
                # Generated query depends on tables existing.
                #
                # WITHOUT THIS:
                # -------------------------------------------------
                # Query execution fails immediately.



        # =================================================
        # EXECUTE GENERATED SQL QUERY
        # =================================================

        cursor.execute(query)

        # WHY THIS IS THE CORE STEP:
        # -------------------------------------------------
        # Executes AI-generated SQL query.
        #
        # THIS VALIDATES:
        # -------------------------------------------------
        # - syntax correctness
        # - schema alignment
        # - executable semantics
        #
        # POSSIBLE FAILURES:
        # -------------------------------------------------
        # - hallucinated tables
        # - missing columns
        # - malformed syntax
        # - unsupported SQLite syntax
        #
        # IMPORTANT:
        # -------------------------------------------------
        # This step transforms:
        #
        # AI text
        #     ↓
        # executable database logic



        # =================================================
        # FETCH QUERY RESULTS
        # =================================================

        result = cursor.fetchall()

        # WHAT fetchall() DOES:
        # -------------------------------------------------
        # Retrieves all query output rows.
        #
        # EXAMPLE:
        # -------------------------------------------------
        # SELECT * FROM employees;
        #
        # →
        #
        # [
        #   (1, "John"),
        #   (2, "Alice")
        # ]
        #
        # WHY IMPORTANT:
        # -------------------------------------------------
        # Allows:
        # - displaying results
        # - evaluating correctness
        # - benchmarking model accuracy
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # + simple retrieval
        # - high memory for massive outputs
        #
        # PRODUCTION:
        # -------------------------------------------------
        # Large systems often stream rows incrementally.



        # =================================================
        # SUCCESS RESPONSE
        # =================================================

        return True, result

        # WHY RETURN TUPLE:
        # -------------------------------------------------
        # Provides:
        # success status + payload
        #
        # STRUCTURE:
        # -------------------------------------------------
        # (True, actual_results)
        #
        # BENEFIT:
        # -------------------------------------------------
        # Simple caller-side handling.
        #
        # Example:
        # -------------------------------------------------
        # success, data = execute_sql(...)
        #
        # if success:
        #     ...
        # else:
        #     ...



    # =====================================================
    # EXCEPTION HANDLING
    # =====================================================

    except Exception as e:

        # WHY CATCH GENERIC EXCEPTIONS:
        # -------------------------------------------------
        # SQL execution can fail in many ways:
        #
        # - syntax errors
        # - runtime DB errors
        # - schema mismatches
        # - malformed SQL
        #
        # Generic exception ensures:
        # -------------------------------------------------
        # application does not crash.
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # + robust handling
        # - less granular debugging
        #
        # PRODUCTION:
        # -------------------------------------------------
        # Better to catch:
        # - sqlite3.OperationalError
        # - sqlite3.SyntaxError
        # etc.



        return False, str(e)

        # WHY CONVERT EXCEPTION TO STRING:
        # -------------------------------------------------
        # Makes error human-readable.
        #
        # Example:
        # -------------------------------------------------
        # "no such table: employees"
        #
        # Useful for:
        # -------------------------------------------------
        # - debugging
        # - evaluation
        # - UI feedback
        #
        # THIS IS IMPORTANT FOR:
        # -------------------------------------------------
        # AI system observability.



    # =====================================================
    # RESOURCE CLEANUP
    # =====================================================

    finally:

        conn.close()

        # WHY finally EXISTS:
        # -------------------------------------------------
        # Ensures cleanup ALWAYS happens.
        #
        # Even if:
        # -------------------------------------------------
        # - SQL crashes
        # - exceptions occur
        #
        # WHY conn.close() IS CRITICAL:
        # -------------------------------------------------
        # Prevents:
        # - memory leaks
        # - locked resources
        # - dangling DB connections
        #
        # THIS IS GOOD ENGINEERING PRACTICE.
        #
        # IMPORTANT:
        # -------------------------------------------------
        # finally block ALWAYS executes.

In [ ]:
# =========================================================
# MODEL EVALUATION FUNCTION
# =========================================================

def evaluate_model(model, tokenizer, dataset, num_samples=50):

    """
    Evaluates SQL-generation model using execution accuracy.

    PURPOSE:
    ---------------------------------------------------------
    Measures whether generated SQL produces the SAME RESULTS
    as ground-truth SQL.

    WHY THIS MATTERS:
    ---------------------------------------------------------
    In Text-to-SQL systems:
    syntax alone is NOT enough.

    Two SQL queries may:
    - look different
    - use different joins/order
    - use aliases differently

    BUT still produce identical outputs.

    Therefore:
    ---------------------------------------------------------
    Execution correctness is more important than
    exact string matching.

    THIS IS A VERY IMPORTANT INDUSTRY CONCEPT.

    INPUTS:
    ---------------------------------------------------------
    model:
        Fine-tuned LLM

    tokenizer:
        Converts text ↔ tokens

    dataset:
        Evaluation dataset

    num_samples:
        Number of samples to test

    OUTPUT:
    ---------------------------------------------------------
    Execution accuracy score
    """



    # =====================================================
    # TRACK CORRECT PREDICTIONS
    # =====================================================

    correct = 0

    # WHY INITIALIZE TO 0:
    # -----------------------------------------------------
    # Counter tracks successful predictions.
    #
    # WHY 0 INSTEAD OF 1:
    # -----------------------------------------------------
    # Counting begins with no correct samples yet.
    #
    # If initialized incorrectly:
    # -----------------------------------------------------
    # accuracy becomes mathematically wrong.
    #
    # THIS IS BASIC METRIC INITIALIZATION LOGIC.



    # =====================================================
    # LIMIT DATASET SIZE
    # =====================================================

    samples = dataset.select(range(num_samples))

    # WHY LIMIT SAMPLE COUNT:
    # -----------------------------------------------------
    # Full evaluation can be expensive.
    #
    # Each sample requires:
    # -----------------------------------------------------
    # 1. LLM inference
    # 2. SQL execution
    # 3. Result comparison
    #
    # LLM inference is computationally heavy.
    #
    # WHY 50 DEFAULT:
    # -----------------------------------------------------
    # Good balance between:
    # - evaluation speed
    # - statistical usefulness
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # Fewer samples:
    # + faster evaluation
    # - noisier metric
    #
    # More samples:
    # + more reliable accuracy
    # - slower evaluation
    #
    # INDUSTRY NOTE:
    # -----------------------------------------------------
    # Large benchmark evaluations may use:
    # thousands of samples.



    # =====================================================
    # ITERATE THROUGH EVALUATION SAMPLES
    # =====================================================

    for sample in samples:

        # WHY ITERATION:
        # -------------------------------------------------
        # Each sample must be independently:
        # - generated
        # - executed
        # - compared
        #
        # This is standard evaluation pipeline logic.
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Sequential evaluation:
        # + simple
        # - slower
        #
        # PRODUCTION:
        # -------------------------------------------------
        # Often parallelized/batched.



        # =================================================
        # EXTRACT QUESTION
        # =================================================

        question = sample["sql_prompt"]

        # WHAT THIS IS:
        # -------------------------------------------------
        # Natural language query.
        #
        # Example:
        # -------------------------------------------------
        # "Show all employees earning > 50000"
        #
        # WHY IMPORTANT:
        # -------------------------------------------------
        # This is the actual user intent
        # model must understand.



        # =================================================
        # EXTRACT DATABASE SCHEMA
        # =================================================

        schema = sample["sql_context"]

        # WHAT THIS CONTAINS:
        # -------------------------------------------------
        # Database structure:
        # - tables
        # - columns
        # - relationships
        #
        # WHY CRITICAL:
        # -------------------------------------------------
        # LLM needs grounding information.
        #
        # OTHERWISE:
        # -------------------------------------------------
        # hallucinated SQL increases dramatically.
        #
        # THIS IS CALLED:
        # -------------------------------------------------
        # schema grounding



        # =================================================
        # EXTRACT GROUND TRUTH SQL
        # =================================================

        gold_sql = sample["sql"]

        # WHAT THIS IS:
        # -------------------------------------------------
        # Human-written correct SQL query.
        #
        # PURPOSE:
        # -------------------------------------------------
        # Acts as benchmark reference.
        #
        # WHY "GOLD":
        # -------------------------------------------------
        # Standard ML terminology:
        #
        # "gold standard"
        #
        # meaning:
        # trusted correct answer.



        # =================================================
        # GENERATE MODEL PREDICTION
        # =================================================

        pred_sql = generate_sql(question, schema)

        # WHAT HAPPENS HERE:
        # -------------------------------------------------
        # LLM performs inference.
        #
        # Pipeline:
        # -------------------------------------------------
        # question + schema
        #       ↓
        # tokenization
        #       ↓
        # transformer inference
        #       ↓
        # autoregressive decoding
        #       ↓
        # predicted SQL
        #
        # THIS IS THE CORE MODEL TEST.



        # =================================================
        # EXECUTE GENERATED SQL
        # =================================================

        pred_ok, pred_res = execute_sql(schema, pred_sql)

        # WHAT THIS RETURNS:
        # -------------------------------------------------
        # pred_ok:
        #   whether execution succeeded
        #
        # pred_res:
        #   query output OR error message
        #
        # WHY EXECUTION MATTERS:
        # -------------------------------------------------
        # String similarity is insufficient.
        #
        # Correctness depends on:
        # actual database behavior.
        #
        # THIS IS EXECUTION-BASED EVALUATION.



        # =================================================
        # EXECUTE GROUND TRUTH SQL
        # =================================================

        gold_ok, gold_res = execute_sql(schema, gold_sql)

        # WHY EXECUTE GROUND TRUTH TOO:
        # -------------------------------------------------
        # Need actual expected result set.
        #
        # Comparison target:
        # -------------------------------------------------
        # predicted_result
        # vs
        # ground_truth_result
        #
        # IMPORTANT:
        # -------------------------------------------------
        # This avoids comparing raw SQL text.
        #
        # WHICH IS IMPORTANT BECAUSE:
        # -------------------------------------------------
        # Multiple SQL queries may be semantically identical.



        # =================================================
        # RESULT COMPARISON
        # =================================================

        if pred_ok and gold_ok and pred_res == gold_res:

            # WHY THIS CONDITION:
            # ---------------------------------------------
            # SUCCESS requires:
            #
            # 1. predicted query executes
            # 2. ground truth executes
            # 3. outputs match exactly
            #
            # THIS IS STRICT EXECUTION ACCURACY.
            #
            # WHY RESULT EQUALITY:
            # ---------------------------------------------
            # Measures semantic correctness.
            #
            # EXAMPLE:
            # -------------------------------------------------
            # Different SQL:
            #
            # SELECT name FROM users;
            #
            # vs
            #
            # SELECT users.name FROM users;
            #
            # May still produce same results.
            #
            # STRING MATCHING WOULD FAIL.
            #
            # EXECUTION MATCHING SUCCEEDS.
            #
            # THIS IS A MAJOR INDUSTRY CONCEPT.



            correct += 1

            # WHY INCREMENT:
            # ---------------------------------------------
            # Counts successful predictions.
            #
            # THIS BUILDS ACCURACY METRIC.
            #
            # TIME COMPLEXITY:
            # -------------------------------------------------
            # O(n)
            #
            # where:
            # n = number of evaluation samples.



    # =====================================================
    # COMPUTE FINAL ACCURACY
    # =====================================================

    accuracy = correct / num_samples

    # WHY THIS FORMULA:
    # -----------------------------------------------------
    # Standard classification accuracy:
    #
    # correct_predictions / total_predictions
    #
    # RESULT:
    # -----------------------------------------------------
    # value between:
    #
    # 0.0 → 1.0
    #
    # INTERPRETATION:
    # -----------------------------------------------------
    # 0.80
    #
    # means:
    # 80% execution correctness.
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # This metric estimates:
    # real-world usability.



    # =====================================================
    # DISPLAY METRIC
    # =====================================================

    print(f"✅ Execution Accuracy: {accuracy:.2f}")

    # WHY :.2f:
    # -----------------------------------------------------
    # Formats floating-point number to 2 decimals.
    #
    # Example:
    # -----------------------------------------------------
    # 0.823478
    #
    # →
    #
    # 0.82
    #
    # BENEFITS:
    # -----------------------------------------------------
    # + cleaner logs
    # + easier readability
    #
    # THIS IS STANDARD REPORTING PRACTICE.



    # =====================================================
    # RETURN FINAL METRIC
    # =====================================================

    return accuracy

    # WHY RETURN VALUE:
    # -----------------------------------------------------
    # Allows:
    # - logging
    # - benchmarking
    # - hyperparameter tuning
    # - dashboard integration
    #
    # PRODUCTION SYSTEMS:
    # -----------------------------------------------------
    # Usually store metrics in:
    # - MLflow
    # - Weights & Biases
    # - TensorBoard

In [ ]:
evaluate_model(model, tokenizer, dataset["test"])

Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

✅ Execution Accuracy: 0.00

0.0

In [ ]:
# =========================================================
# SELECT SMALL TEST SUBSET
# =========================================================

samples = dataset["test"].select(range(5))

# WHAT THIS DOES:
# ---------------------------------------------------------
# Extracts first 5 samples from test dataset.
#
# WHY TEST DATASET:
# ---------------------------------------------------------
# Test set contains:
# - unseen examples
# - evaluation-only samples
#
# IMPORTANT ML PRINCIPLE:
# ---------------------------------------------------------
# Model should NOT be evaluated on training data.
#
# OTHERWISE:
# ---------------------------------------------------------
# Results become misleading because model may memorize.
#
# THIS IS CALLED:
# ---------------------------------------------------------
# data leakage
#
# WHY select(range(5)):
# ---------------------------------------------------------
# Limits evaluation to small human-readable subset.
#
# WHY 5:
# ---------------------------------------------------------
# Small enough for manual inspection.
#
# PURPOSE:
# ---------------------------------------------------------
# Developer debugging
# and qualitative evaluation.
#
# TRADE-OFF:
# ---------------------------------------------------------
# + fast
# + readable
# - statistically insignificant
#
# INDUSTRY NOTE:
# ---------------------------------------------------------
# Manual inspection is STILL extremely important,
# even in modern LLM systems.
#
# Quantitative metrics alone are insufficient.



# =========================================================
# ITERATE THROUGH TEST SAMPLES
# =========================================================

for sample in samples:

    # WHY LOOP THROUGH SAMPLES:
    # -----------------------------------------------------
    # Each test example is independently evaluated.
    #
    # FLOW:
    # -----------------------------------------------------
    # extract input
    # generate SQL
    # compare outputs
    # print results
    #
    # THIS IS A QUALITATIVE EVALUATION LOOP.



    # =====================================================
    # EXTRACT NATURAL LANGUAGE QUESTION
    # =====================================================

    question = sample["sql_prompt"]

    # WHAT THIS REPRESENTS:
    # -----------------------------------------------------
    # User request in natural language.
    #
    # Example:
    # -----------------------------------------------------
    # "Show all customers from California"
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # This is the semantic intent the model must interpret.
    #
    # TEXT-TO-SQL CORE PROBLEM:
    # -----------------------------------------------------
    # Human language
    #          ↓
    # structured database query



    # =====================================================
    # EXTRACT DATABASE SCHEMA
    # =====================================================

    schema = sample["sql_context"]

    # WHAT THIS CONTAINS:
    # -----------------------------------------------------
    # Database structure information:
    #
    # - tables
    # - columns
    # - relationships
    # - types
    #
    # WHY CRITICAL:
    # -----------------------------------------------------
    # LLM must understand:
    # - available tables
    # - valid columns
    # - relational structure
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # hallucinated SQL increases dramatically.
    #
    # THIS IS CALLED:
    # -----------------------------------------------------
    # schema grounding



    # =====================================================
    # EXTRACT GROUND-TRUTH SQL
    # =====================================================

    gold_sql = sample["sql"]

    # WHAT THIS IS:
    # -----------------------------------------------------
    # Human-written correct SQL answer.
    #
    # PURPOSE:
    # -----------------------------------------------------
    # Acts as benchmark reference.
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Allows:
    # - human comparison
    # - correctness analysis
    # - debugging
    #
    # THIS IS THE EXPECTED OUTPUT.



    # =====================================================
    # GENERATE MODEL PREDICTION
    # =====================================================

    pred_sql = generate_sql(question, schema)

    # WHAT HAPPENS HERE:
    # -----------------------------------------------------
    # LLM inference pipeline executes.
    #
    # PROCESS:
    # -----------------------------------------------------
    # question + schema
    #       ↓
    # prompt formatting
    #       ↓
    # tokenization
    #       ↓
    # transformer inference
    #       ↓
    # autoregressive generation
    #       ↓
    # predicted SQL
    #
    # THIS IS THE ACTUAL MODEL TEST.
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # This evaluates:
    # - reasoning ability
    # - schema understanding
    # - SQL syntax knowledge
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # Sequential inference:
    # + simpler
    # - slower than batching



    # =====================================================
    # PRINT VISUAL SEPARATOR
    # =====================================================

    print("\n===================")

    # WHY SEPARATOR EXISTS:
    # -----------------------------------------------------
    # Improves console readability.
    #
    # WITHOUT THIS:
    # -----------------------------------------------------
    # Outputs become visually cluttered.
    #
    # THIS IS SIMPLE BUT IMPORTANT UX DESIGN.
    #
    # DEBUGGING READABILITY MATTERS.



    # =====================================================
    # DISPLAY QUESTION
    # =====================================================

    print("QUESTION:\n", question)

    # WHY PRINT QUESTION:
    # -----------------------------------------------------
    # Developer needs:
    # - original user intent
    # - context for evaluation
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # SQL comparison lacks semantic context.
    #
    # HUMAN REVIEW:
    # -----------------------------------------------------
    # Important for identifying:
    # - ambiguity
    # - reasoning failures
    # - misunderstanding patterns



    # =====================================================
    # DISPLAY GROUND-TRUTH SQL
    # =====================================================

    print("\nGOLD SQL:\n", gold_sql)

    # WHY PRINT GOLD SQL:
    # -----------------------------------------------------
    # Shows expected correct query.
    #
    # PURPOSE:
    # -----------------------------------------------------
    # Allows side-by-side comparison with prediction.
    #
    # HUMAN ANALYSIS:
    # -----------------------------------------------------
    # Developers can inspect:
    # - joins
    # - filters
    # - aggregation logic
    # - correctness
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # Exact SQL text may differ from prediction,
    # while still being semantically equivalent.
    #
    # THIS IS WHY:
    # -----------------------------------------------------
    # execution accuracy matters more than string matching.



    # =====================================================
    # DISPLAY PREDICTED SQL
    # =====================================================

    print("\nPREDICTED SQL:\n", pred_sql)

    # WHY PRINT PREDICTION:
    # -----------------------------------------------------
    # Enables qualitative model inspection.
    #
    # VERY IMPORTANT:
    # -----------------------------------------------------
    # Manual inspection reveals issues metrics may miss:
    #
    # - hallucinated tables
    # - verbose outputs
    # - malformed SQL
    # - prompt leakage
    # - repeated tokens
    # - reasoning errors
    #
    # INDUSTRY REALITY:
    # -----------------------------------------------------
    # Human evaluation remains critical in LLM engineering.
    #
    # AUTOMATED METRICS ARE NOT ENOUGH.

Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

===================
QUESTION:
 What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?

GOLD SQL:
 SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

PREDICTED SQL:
 ### Question:
What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?

### Schema:
CREATE TABLE creative_ai (application_id INT, name TEXT, region TEXT, explainability_score FLOAT); INSERT INTO creative_ai (application_id, name, region, explainability_score) VALUES (1, 'ApplicationX', 'Europe', 0.87), (2, 'ApplicationY', 'North America', 0.91), (3, 'ApplicationZ', 'Europe', 0.84), (4, 'ApplicationAA', 'North America', 0.93), (5, 'ApplicationAB', 'Europe', 0.89);

### SQL:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

### Result:
0.90

Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

===================
QUESTION:
 Delete all records of rural infrastructure projects in Indonesia that have a completion date before 2010.

GOLD SQL:
 DELETE FROM rural_infrastructure WHERE country = 'Indonesia' AND completion_date < '2010-01-01';

PREDICTED SQL:
 ### Question:
Delete all records of rural infrastructure projects in Indonesia that have a completion date before 2010.

### Schema:
CREATE TABLE rural_infrastructure (id INT, project_name TEXT, sector TEXT, country TEXT, completion_date DATE); INSERT INTO rural_infrastructure (id, project_name, sector, country, completion_date) VALUES (1, 'Water Supply Expansion', 'Infrastructure', 'Indonesia', '2008-05-15'), (2, 'Rural Electrification', 'Infrastructure', 'Indonesia', '2012-08-28'), (3, 'Transportation Improvement', 'Infrastructure', 'Indonesia', '2009-12-31');

### SQL:
DELETE FROM rural_infrastructure WHERE completion_date < '2010-01-01';

### Result:
After running the SQL query, the table will be updated to only contain the record with id = 2.

/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

===================
QUESTION:
 How many accidents have been recorded for SpaceX and Blue Origin rocket launches?

GOLD SQL:
 SELECT launch_provider, COUNT(*) FROM Accidents GROUP BY launch_provider;

PREDICTED SQL:
 ### Question:
How many accidents have been recorded for SpaceX and Blue Origin rocket launches?

### Schema:
CREATE TABLE Accidents (id INT, launch_provider VARCHAR(255), year INT, description TEXT); INSERT INTO Accidents (id, launch_provider, year, description) VALUES (1, 'SpaceX', 2015, 'Falcon 9 explosion'), (2, 'Blue Origin', 2011, 'Propulsion system failure'), (3, 'SpaceX', 2016, 'Falcon 9 explosion');

### SQL:
SELECT COUNT(*) FROM Accidents WHERE launch_provider = 'SpaceX' AND year = 2015;

Both `max_new_tokens` (=100) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

===================
QUESTION:
 What is the maximum quantity of seafood sold in a single transaction?

GOLD SQL:
 SELECT MAX(quantity) FROM sales;

PREDICTED SQL:
 ### Question:
What is the maximum quantity of seafood sold in a single transaction?

### Schema:
CREATE TABLE sales (id INT, location VARCHAR(20), quantity INT, price DECIMAL(5,2)); INSERT INTO sales (id, location, quantity, price) VALUES (1, 'Northeast', 50, 12.99), (2, 'Midwest', 75, 19.99), (3, 'West', 120, 14.49);

### SQL:
SELECT MAX(quantity) FROM sales;

### Output:
120


===================
QUESTION:
 What is the total budget for movies released before 2010?

GOLD SQL:
 SELECT SUM(budget) FROM Movies_Release_Year WHERE release_year < 2010;

PREDICTED SQL:
 ### Question:
What is the total budget for movies released before 2010?

### Schema:
CREATE TABLE Movies_Release_Year (id INT, title VARCHAR(100), release_year INT, budget DECIMAL(10,2)); INSERT INTO Movies_Release_Year (id, title, release_year, budget) VALUES (1, 'The Matrix', 1999, 63000000.00), (2, 'Titanic', 1997, 200000000.00), (3, 'The Lord of the Rings: The Fellowship of the Ring', 2001, 93000000.00);

### SQL:
SELECT SUM(budget) FROM Movies_Release_Year WHERE release_year < 2010;

### Answer:
The total budget for movies released before 2010 is 186000000.00.

In [ ]:
# =========================================================
# SQL GENERATION FUNCTION
# =========================================================

def generate_sql(question, schema):

    """
    Generates clean SQL queries using the fine-tuned LLM.

    PURPOSE:
    ---------------------------------------------------------
    Converts:
        natural language question + schema
    into:
        executable SQL query

    WHY THIS VERSION IS IMPROVED:
    ---------------------------------------------------------
    Compared to earlier implementation, this version adds:

    + deterministic generation
    + output cleanup
    + SQL extraction logic
    + stopping control
    + safer decoding behavior

    This makes the system:
    ---------------------------------------------------------
    - more production-friendly
    - more stable
    - less hallucination-prone

    INDUSTRY NOTE:
    ---------------------------------------------------------
    Raw LLM outputs are often messy.
    Postprocessing is essential in real systems.
    """



    # =====================================================
    # CREATE STRUCTURED PROMPT
    # =====================================================

    prompt = f"""### Question:
{question}

### Schema:
{schema}

### SQL:
"""

    # WHY STRUCTURED PROMPTING:
    # -----------------------------------------------------
    # LLMs are highly pattern-sensitive.
    #
    # During training:
    # -----------------------------------------------------
    # Model learned this exact format.
    #
    # Therefore inference should preserve:
    # -----------------------------------------------------
    # - same headers
    # - same ordering
    # - same structure
    #
    # THIS IS CALLED:
    # -----------------------------------------------------
    # prompt-template alignment
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Consistent formatting improves:
    # - instruction following
    # - SQL quality
    # - output stability
    #
    # SECTION PURPOSES:
    # -----------------------------------------------------
    # ### Question:
    #     user intent
    #
    # ### Schema:
    #     database grounding
    #
    # ### SQL:
    #     generation target
    #
    # WHY END WITH "### SQL:":
    # -----------------------------------------------------
    # This acts as generation anchor.
    #
    # Model understands:
    # -----------------------------------------------------
    # "Now I should generate SQL"
    #
    # WITHOUT THIS:
    # -----------------------------------------------------
    # model may:
    # - continue explaining
    # - generate prose
    # - produce malformed outputs



    # =====================================================
    # TOKENIZE INPUT PROMPT
    # =====================================================

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    # WHAT TOKENIZATION DOES:
    # -----------------------------------------------------
    # Converts raw text into token IDs.
    #
    # LLMs operate numerically:
    # -----------------------------------------------------
    # text
    #   ↓
    # token IDs
    #   ↓
    # embeddings
    #   ↓
    # transformer computation
    #
    # WHY return_tensors="pt":
    # -----------------------------------------------------
    # Returns PyTorch tensors directly.
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # tokenizer outputs Python lists.
    #
    # WHY .to("cuda"):
    # -----------------------------------------------------
    # Moves tensors onto GPU.
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # Model and tensors must reside on same device.
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # runtime device mismatch errors occur.
    #
    # GPU BENEFITS:
    # -----------------------------------------------------
    # + massively faster inference
    # + parallel tensor computation
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + speed
    # - requires CUDA-capable GPU
    #
    # PRODUCTION IMPROVEMENT:
    # -----------------------------------------------------
    # Better:
    #
    # .to(model.device)
    #
    # instead of hardcoded "cuda"



    # =====================================================
    # AUTOREGRESSIVE TEXT GENERATION
    # =====================================================

    outputs = model.generate(

        # -------------------------------------------------
        # INPUT TENSORS
        # -------------------------------------------------

        **inputs,

        # WHY **inputs:
        # -------------------------------------------------
        # Expands tokenizer dictionary into:
        #
        # input_ids=...
        # attention_mask=...
        #
        # generate() expects keyword arguments.



        # -------------------------------------------------
        # MAX GENERATED TOKENS
        # -------------------------------------------------

        max_new_tokens=80,

        # WHAT THIS CONTROLS:
        # -------------------------------------------------
        # Maximum number of NEW tokens generated.
        #
        # IMPORTANT:
        # -------------------------------------------------
        # Does NOT include prompt length.
        #
        # WHY 80:
        # -------------------------------------------------
        # SQL queries are typically concise.
        #
        # BENEFITS:
        # -------------------------------------------------
        # + lower latency
        # + reduced hallucination
        # + lower compute cost
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Too small:
        # - truncates complex SQL
        #
        # Too large:
        # - verbose outputs
        # - hallucinations
        # - slower generation
        #
        # GENERATION COST:
        # -------------------------------------------------
        # Autoregressive generation scales linearly:
        #
        # O(n)
        #
        # where:
        # n = generated tokens



        # -------------------------------------------------
        # TEMPERATURE
        # -------------------------------------------------

        temperature=0.1,

        # WHAT TEMPERATURE DOES:
        # -------------------------------------------------
        # Controls randomness in token sampling.
        #
        # LOW TEMPERATURE:
        # -------------------------------------------------
        # More deterministic
        # More confident predictions
        #
        # HIGH TEMPERATURE:
        # -------------------------------------------------
        # More random/creative outputs
        #
        # WHY 0.1 FOR SQL:
        # -------------------------------------------------
        # SQL generation needs:
        # - precision
        # - consistency
        # - correctness
        #
        # NOT creativity.
        #
        # BENEFITS:
        # -------------------------------------------------
        # + stable SQL
        # + reproducible outputs
        # + lower hallucination
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # + reliability
        # - less diversity
        #
        # TYPICAL USAGE:
        # -------------------------------------------------
        # Coding/SQL:
        #   0.0 → 0.2
        #
        # Creative writing:
        #   0.7 → 1.2



        # -------------------------------------------------
        # DETERMINISTIC DECODING
        # -------------------------------------------------

        do_sample=False,

        # WHAT THIS DOES:
        # -------------------------------------------------
        # Disables probabilistic token sampling.
        #
        # INSTEAD:
        # -------------------------------------------------
        # model selects highest-probability token each step.
        #
        # THIS IS:
        # -------------------------------------------------
        # greedy decoding
        #
        # WHY IMPORTANT:
        # -------------------------------------------------
        # SQL should be deterministic and repeatable.
        #
        # BENEFITS:
        # -------------------------------------------------
        # + stable outputs
        # + reproducibility
        # + fewer hallucinations
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # + consistency
        # - less exploration
        #
        # INDUSTRY NOTE:
        # -------------------------------------------------
        # Most code-generation systems use:
        # - greedy decoding
        # OR
        # - low-temperature sampling



        # -------------------------------------------------
        # PADDING TOKEN
        # -------------------------------------------------

        pad_token_id=tokenizer.eos_token_id,

        # WHY THIS EXISTS:
        # -------------------------------------------------
        # Some models lack explicit pad token.
        #
        # Using EOS token prevents:
        # -------------------------------------------------
        # generation warnings/errors.
        #
        # EOS:
        # -------------------------------------------------
        # End-of-sequence token
        #
        # WHY SAFE:
        # -------------------------------------------------
        # During inference:
        # padding should behave as "sequence ended".
        #
        # WITHOUT THIS:
        # -------------------------------------------------
        # Transformers may:
        # - throw warnings
        # - behave inconsistently
    )



    # =====================================================
    # DECODE GENERATED TOKENS
    # =====================================================

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    # WHAT decode() DOES:
    # -----------------------------------------------------
    # Converts token IDs back into readable text.
    #
    # WHY outputs[0]:
    # -----------------------------------------------------
    # generate() returns batched output:
    #
    # [batch_size, seq_len]
    #
    # outputs[0]:
    # -----------------------------------------------------
    # selects first prediction sequence.
    #
    # WHY skip_special_tokens=True:
    # -----------------------------------------------------
    # Removes:
    # - <bos>
    # - <eos>
    # - <pad>
    #
    # BENEFIT:
    # -----------------------------------------------------
    # cleaner output text



    # =====================================================
    # EXTRACT ONLY SQL SECTION
    # =====================================================

    if "### SQL:" in response:

        response = response.split("### SQL:")[-1]

        # WHY THIS EXTRACTION EXISTS:
        # -------------------------------------------------
        # Decoded response may include:
        # - original prompt
        # - repeated headers
        # - extra text
        #
        # Example:
        # -------------------------------------------------
        # ### Question:
        # ...
        #
        # ### SQL:
        # SELECT * FROM users;
        #
        # We only want:
        # -------------------------------------------------
        # SELECT * FROM users;
        #
        # WHY split()[-1]:
        # -------------------------------------------------
        # Takes content AFTER final SQL marker.
        #
        # BENEFIT:
        # -------------------------------------------------
        # cleaner production outputs
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # naive string parsing
        #
        # Production systems often use:
        # - regex extraction
        # - AST parsing



    # =====================================================
    # FORCE SQL TERMINATION
    # =====================================================

    if ";" in response:

        response = response.split(";")[0] + ";"

        # WHY THIS EXISTS:
        # -------------------------------------------------
        # LLMs may continue generating:
        # - explanations
        # - repeated queries
        # - additional garbage text
        #
        # SQL convention:
        # -------------------------------------------------
        # semicolon marks statement termination.
        #
        # THIS LOGIC:
        # -------------------------------------------------
        # Keeps ONLY first SQL statement.
        #
        # BENEFITS:
        # -------------------------------------------------
        # + cleaner output
        # + safer execution
        # + easier validation
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Multi-statement queries get truncated.
        #
        # PRODUCTION:
        # -------------------------------------------------
        # Better systems use:
        # - SQL parsers
        # - AST validation
        # - structured decoding



    # =====================================================
    # FINAL CLEANUP
    # =====================================================

    return response.strip()

    # WHY strip():
    # -----------------------------------------------------
    # Removes:
    # - leading spaces
    # - trailing spaces
    # - extra newlines
    #
    # BENEFITS:
    # -----------------------------------------------------
    # + cleaner display
    # + easier execution
    # + more consistent formatting

In [20]:
question = "Show all employee names"

schema = """
CREATE TABLE employees (
    id INT,
    name TEXT,
    salary INT
);
"""

result = generate_sql(question, schema)

print("Generated SQL:")
print(result)

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated SQL:
SELECT name FROM employees;

In [ ]:
# =========================================================
# SQL KEYWORD SIMILARITY FUNCTION
# =========================================================

def keyword_similarity(pred, gold):

    """
    Computes keyword-level similarity between
    predicted SQL and ground-truth SQL.

    PURPOSE:
    ---------------------------------------------------------
    Measures lexical overlap between:
    - model-generated SQL
    - expected SQL

    OUTPUT:
    ---------------------------------------------------------
    Returns similarity score between:

        0.0 → 1.0

    WHERE:
    ---------------------------------------------------------
    1.0  = identical keyword sets
    0.0  = no shared keywords

    WHY THIS METRIC EXISTS:
    ---------------------------------------------------------
    Sometimes execution evaluation is:
    - expensive
    - unavailable
    - difficult

    Keyword similarity provides:
    ---------------------------------------------------------
    quick approximate comparison.

    IMPORTANT:
    ---------------------------------------------------------
    This is NOT semantic evaluation.
    It only measures token overlap.

    INDUSTRY NOTE:
    ---------------------------------------------------------
    This resembles:
    - Jaccard similarity
    - bag-of-words comparison
    - lexical overlap metrics
    """



    # =====================================================
    # NORMALIZE PREDICTED SQL
    # =====================================================

    pred_words = set(pred.lower().split())

    # STEP-BY-STEP BREAKDOWN:
    # -----------------------------------------------------
    # pred.lower()
    # -----------------------------------------------------
    # Converts SQL to lowercase.
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # SQL is generally case-insensitive.
    #
    # Example:
    # -----------------------------------------------------
    # SELECT
    # select
    #
    # should be treated equally.
    #
    # WITHOUT lower():
    # -----------------------------------------------------
    # similarity becomes artificially lower.
    #
    #
    # split()
    # -----------------------------------------------------
    # Splits sentence into words/tokens using whitespace.
    #
    # Example:
    # -----------------------------------------------------
    # "SELECT * FROM users"
    #
    # →
    #
    # ["SELECT", "*", "FROM", "users"]
    #
    #
    # set(...)
    # -----------------------------------------------------
    # Converts list into unique-word collection.
    #
    # WHY USE SET:
    # -----------------------------------------------------
    # Removes duplicates automatically.
    #
    # Example:
    # -----------------------------------------------------
    # ["select", "select", "from"]
    #
    # →
    #
    # {"select", "from"}
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Similarity measures shared vocabulary,
    # not frequency.
    #
    # THIS IS BAG-OF-WORDS STYLE COMPARISON.
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # + simple
    # + fast
    # - ignores word order
    # - ignores syntax
    # - ignores semantics



    # =====================================================
    # NORMALIZE GROUND-TRUTH SQL
    # =====================================================

    gold_words = set(gold.lower().split())

    # SAME LOGIC AS ABOVE:
    # -----------------------------------------------------
    # Normalize:
    # - casing
    # - spacing
    #
    # Then convert into unique token set.
    #
    # WHY CONSISTENT NORMALIZATION MATTERS:
    # -----------------------------------------------------
    # Comparison metrics require:
    # identical preprocessing pipelines.
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # metrics become unreliable.



    # =====================================================
    # COMPUTE WORD OVERLAP
    # =====================================================

    overlap = len(pred_words & gold_words)

    # WHAT "&" DOES:
    # -----------------------------------------------------
    # Set intersection operator.
    #
    # RETURNS:
    # -----------------------------------------------------
    # words appearing in BOTH sets.
    #
    # EXAMPLE:
    # -----------------------------------------------------
    # pred:
    # {"select", "from", "users"}
    #
    # gold:
    # {"select", "from", "employees"}
    #
    # intersection:
    # {"select", "from"}
    #
    # overlap = 2
    #
    # WHY len():
    # -----------------------------------------------------
    # Counts shared keywords.
    #
    # THIS REPRESENTS:
    # -----------------------------------------------------
    # lexical similarity.
    #
    # TIME COMPLEXITY:
    # -----------------------------------------------------
    # Set intersection is approximately:
    #
    # O(min(n, m))
    #
    # Very efficient.
    #
    # BENEFIT:
    # -----------------------------------------------------
    # Fast even for larger token sets.



    # =====================================================
    # COMPUTE TOTAL UNIQUE WORDS
    # =====================================================

    total = len(pred_words | gold_words)

    # WHAT "|" DOES:
    # -----------------------------------------------------
    # Set union operator.
    #
    # RETURNS:
    # -----------------------------------------------------
    # all unique words from BOTH sets.
    #
    # EXAMPLE:
    # -----------------------------------------------------
    # pred:
    # {"select", "from", "users"}
    #
    # gold:
    # {"select", "from", "employees"}
    #
    # union:
    # {"select", "from", "users", "employees"}
    #
    # total = 4
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Union forms denominator of similarity metric.
    #
    # This normalizes score relative to total vocabulary.
    #
    # OTHERWISE:
    # -----------------------------------------------------
    # overlap count alone is misleading.



    # =====================================================
    # COMPUTE SIMILARITY SCORE
    # =====================================================

    return overlap / total

    # THIS IS:
    # -----------------------------------------------------
    # Jaccard Similarity Formula
    #
    # FORMULA:
    # -----------------------------------------------------
    # intersection_size / union_size
    #
    # INTERPRETATION:
    # -----------------------------------------------------
    # 1.0
    #     perfect overlap
    #
    # 0.0
    #     no overlap
    #
    # WHY THIS IS USEFUL:
    # -----------------------------------------------------
    # Provides fast approximate similarity measure.
    #
    # BENEFITS:
    # -----------------------------------------------------
    # + simple
    # + interpretable
    # + efficient
    #
    # MAJOR LIMITATIONS:
    # -----------------------------------------------------
    # - ignores SQL semantics
    # - ignores syntax structure
    # - ignores ordering
    # - ignores query correctness
    #
    # VERY IMPORTANT:
    # -----------------------------------------------------
    # High similarity DOES NOT guarantee:
    # correct SQL execution.
    #
    # Likewise:
    # -----------------------------------------------------
    # low similarity may still produce
    # identical database results.

In [24]:
sample = dataset["test"][0]

pred = generate_sql(
    sample["sql_prompt"],
    sample["sql_context"]
)

gold = sample["sql"]

score = keyword_similarity(pred, gold)

print("Predicted SQL:")
print(pred)

print("\nGold SQL:")
print(gold)

print("\nSimilarity Score:")
print(score)

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Predicted SQL:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

Gold SQL:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

Similarity Score:
1.0

In [ ]:
# =========================================================
# SEMANTIC EVALUATION FUNCTION
# =========================================================

def semantic_evaluation(dataset, num_samples=10):

    """
    Performs lightweight semantic-style evaluation
    for generated SQL queries.

    PURPOSE:
    ---------------------------------------------------------
    Measures approximate similarity between:
    - generated SQL
    - ground-truth SQL

    USING:
    ---------------------------------------------------------
    keyword overlap metric

    IMPORTANT:
    ---------------------------------------------------------
    Despite the function name "semantic_evaluation",
    this is NOT true semantic understanding.

    It is actually:
    ---------------------------------------------------------
    lexical similarity evaluation

    WHY THIS FUNCTION EXISTS:
    ---------------------------------------------------------
    Useful for:
    - quick debugging
    - qualitative inspection
    - lightweight benchmarking
    - monitoring training improvements

    WITHOUT needing:
    ---------------------------------------------------------
    expensive SQL execution.

    OUTPUT:
    ---------------------------------------------------------
    Displays:
    - question
    - generated SQL
    - expected SQL
    - similarity score

    Then computes:
    ---------------------------------------------------------
    average similarity across samples.
    """



    # =====================================================
    # SELECT SMALL EVALUATION SUBSET
    # =====================================================

    samples = dataset.select(range(num_samples))

    # WHAT THIS DOES:
    # -----------------------------------------------------
    # Extracts subset of evaluation samples.
    #
    # WHY SMALL SUBSET:
    # -----------------------------------------------------
    # LLM inference is computationally expensive.
    #
    # Smaller subset:
    # -----------------------------------------------------
    # + faster evaluation
    # + easier debugging
    # + human-readable outputs
    #
    # WHY num_samples=10:
    # -----------------------------------------------------
    # Provides reasonable balance between:
    # - speed
    # - metric stability
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # Small sample size:
    # + fast
    # - statistically noisy
    #
    # LARGE BENCHMARKS:
    # -----------------------------------------------------
    # usually evaluate thousands of examples.



    # =====================================================
    # STORE ALL SIMILARITY SCORES
    # =====================================================

    scores = []

    # WHY LIST EXISTS:
    # -----------------------------------------------------
    # Need to aggregate metrics later.
    #
    # Stores:
    # -----------------------------------------------------
    # per-sample similarity values.
    #
    # EXAMPLE:
    # -----------------------------------------------------
    # [0.75, 0.92, 0.64, ...]
    #
    # WHY EMPTY INITIALIZATION:
    # -----------------------------------------------------
    # Evaluation starts with no collected scores yet.
    #
    # THIS IS STANDARD ACCUMULATION PATTERN.



    # =====================================================
    # ITERATE THROUGH EVALUATION SAMPLES
    # =====================================================

    for sample in samples:

        # WHY ITERATION:
        # -------------------------------------------------
        # Each sample must be independently:
        # - generated
        # - compared
        # - evaluated
        #
        # THIS IS STANDARD ML EVALUATION FLOW.
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Sequential processing:
        # + simple
        # - slower
        #
        # PRODUCTION:
        # -------------------------------------------------
        # Often batched or parallelized.



        # =================================================
        # GENERATE PREDICTED SQL
        # =================================================

        pred = generate_sql(
            sample["sql_prompt"],
            sample["sql_context"]
        )

        # WHAT HAPPENS HERE:
        # -------------------------------------------------
        # LLM inference pipeline executes.
        #
        # INPUTS:
        # -------------------------------------------------
        # sql_prompt:
        #     natural language question
        #
        # sql_context:
        #     database schema
        #
        # OUTPUT:
        # -------------------------------------------------
        # generated SQL query
        #
        # WHY SCHEMA CONTEXT IS IMPORTANT:
        # -------------------------------------------------
        # Prevents hallucinated:
        # - tables
        # - columns
        # - joins
        #
        # THIS IS CALLED:
        # -------------------------------------------------
        # schema grounding



        # =================================================
        # EXTRACT GROUND-TRUTH SQL
        # =================================================

        gold = sample["sql"]

        # WHAT THIS IS:
        # -------------------------------------------------
        # Human-written correct SQL query.
        #
        # PURPOSE:
        # -------------------------------------------------
        # Benchmark reference.
        #
        # IMPORTANT:
        # -------------------------------------------------
        # This is expected/correct output used for evaluation.



        # =================================================
        # COMPUTE SIMILARITY SCORE
        # =================================================

        score = keyword_similarity(pred, gold)

        # WHAT THIS DOES:
        # -------------------------------------------------
        # Computes lexical overlap score between:
        #
        # predicted SQL
        # vs
        # ground-truth SQL
        #
        # METRIC USED:
        # -------------------------------------------------
        # Jaccard similarity
        #
        # RANGE:
        # -------------------------------------------------
        # 0.0 → 1.0
        #
        # IMPORTANT:
        # -------------------------------------------------
        # This measures:
        # shared keywords
        #
        # NOT:
        # actual SQL correctness.
        #
        # HIGH SCORE DOES NOT GUARANTEE:
        # -------------------------------------------------
        # correct execution.
        #
        # LOW SCORE MAY STILL:
        # -------------------------------------------------
        # produce identical results.
        #
        # THIS IS A MAJOR LIMITATION.



        # =================================================
        # STORE SCORE
        # =================================================

        scores.append(score)

        # WHY STORE INDIVIDUAL SCORES:
        # -------------------------------------------------
        # Needed later for:
        # - averaging
        # - statistics
        # - analysis
        #
        # THIS IS STANDARD METRIC AGGREGATION LOGIC.



        # =================================================
        # PRINT VISUAL SEPARATOR
        # =================================================

        print("\n====================")

        # WHY THIS EXISTS:
        # -------------------------------------------------
        # Improves console readability.
        #
        # OTHERWISE:
        # -------------------------------------------------
        # outputs become cluttered and difficult to inspect.
        #
        # HUMAN READABILITY MATTERS
        # during model debugging.



        # =================================================
        # DISPLAY QUESTION
        # =================================================

        print("QUESTION:")
        print(sample["sql_prompt"])

        # WHY PRINT QUESTION:
        # -------------------------------------------------
        # Developer needs:
        # - original user intent
        # - context for analysis
        #
        # HELPS IDENTIFY:
        # -------------------------------------------------
        # reasoning failures
        # ambiguity
        # prompt weaknesses



        # =================================================
        # DISPLAY GENERATED SQL
        # =================================================

        print("\nPREDICTED:")
        print(pred)

        # WHY SHOW PREDICTION:
        # -------------------------------------------------
        # Enables qualitative evaluation.
        #
        # IMPORTANT:
        # -------------------------------------------------
        # Human inspection reveals:
        # - hallucinations
        # - formatting problems
        # - repeated outputs
        # - malformed SQL
        #
        # AUTOMATED METRICS ALONE
        # are insufficient in LLM systems.



        # =================================================
        # DISPLAY GROUND-TRUTH SQL
        # =================================================

        print("\nGOLD:")
        print(gold)

        # WHY SHOW GOLD SQL:
        # -------------------------------------------------
        # Allows side-by-side comparison.
        #
        # Developer can inspect:
        # -------------------------------------------------
        # - joins
        # - filters
        # - aggregations
        # - semantic differences
        #
        # IMPORTANT:
        # -------------------------------------------------
        # SQL text may differ while still producing
        # same execution result.
        #
        # WHICH IS WHY:
        # -------------------------------------------------
        # execution evaluation is superior.



        # =================================================
        # DISPLAY SIMILARITY SCORE
        # =================================================

        print("\nSIMILARITY:")
        print(round(score, 2))

        # WHY round(score, 2):
        # -------------------------------------------------
        # Formats metric to 2 decimal places.
        #
        # EXAMPLE:
        # -------------------------------------------------
        # 0.834293
        #
        # →
        #
        # 0.83
        #
        # BENEFITS:
        # -------------------------------------------------
        # + cleaner logs
        # + easier interpretation
        #
        # THIS IS STANDARD REPORTING PRACTICE.



    # =====================================================
    # COMPUTE AVERAGE SCORE
    # =====================================================

    avg_score = sum(scores) / len(scores)

    # WHAT THIS DOES:
    # -----------------------------------------------------
    # Aggregates overall model performance.
    #
    # FORMULA:
    # -----------------------------------------------------
    # average = total_scores / number_of_samples
    #
    # WHY IMPORTANT:
    # -----------------------------------------------------
    # Single sample performance is noisy.
    #
    # Average score provides:
    # -----------------------------------------------------
    # more stable overall estimate.
    #
    # TIME COMPLEXITY:
    # -----------------------------------------------------
    # O(n)
    #
    # where:
    # n = number of samples



    # =====================================================
    # DISPLAY FINAL METRIC
    # =====================================================

    print("\n✅ Average Semantic Similarity:", round(avg_score, 2))

    # WHY FINAL SUMMARY:
    # -----------------------------------------------------
    # Provides quick high-level metric.
    #
    # Useful for:
    # -----------------------------------------------------
    # - comparing experiments
    # - monitoring training
    # - debugging improvements
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # This metric is approximate only.

In [27]:
semantic_evaluation(dataset["test"], num_samples=5)

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?

PREDICTED:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

GOLD:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

SIMILARITY:
1.0

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
Delete all records of rural infrastructure projects in Indonesia that have a completion date before 2010.

PREDICTED:
DELETE FROM rural_infrastructure WHERE completion_date < '2010-01-01';

GOLD:
DELETE FROM rural_infrastructure WHERE country = 'Indonesia' AND completion_date < '2010-01-01';

SIMILARITY:
0.64

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
How many accidents have been recorded for SpaceX and Blue Origin rocket launches?

PREDICTED:
SELECT COUNT(*) FROM Accidents WHERE launch_provider = 'SpaceX' AND year = 2015;

GOLD:
SELECT launch_provider, COUNT(*) FROM Accidents GROUP BY launch_provider;

SIMILARITY:
0.27

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
What is the maximum quantity of seafood sold in a single transaction?

PREDICTED:
SELECT MAX(quantity) FROM sales;

GOLD:
SELECT MAX(quantity) FROM sales;

SIMILARITY:
1.0

====================
QUESTION:
What is the total budget for movies released before 2010?

PREDICTED:
SELECT SUM(budget) FROM Movies_Release_Year WHERE release_year < 2010;

GOLD:
SELECT SUM(budget) FROM Movies_Release_Year WHERE release_year < 2010;

SIMILARITY:
1.0

✅ Average Semantic Similarity: 0.78

In [49]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# =========================================================
# EXACT MATCH ACCURACY EVALUATION
# =========================================================

def exact_match_accuracy(dataset, num_samples=20):

    """
    Evaluates model performance using exact SQL matching.

    PURPOSE:
    ---------------------------------------------------------
    Measures whether generated SQL query text matches
    the ground-truth SQL query EXACTLY.

    IMPORTANT:
    ---------------------------------------------------------
    This is a STRICT evaluation metric.

    Generated SQL is considered correct ONLY IF:
    ---------------------------------------------------------
    predicted SQL text == ground-truth SQL text

    AFTER:
    ---------------------------------------------------------
    - lowercase normalization
    - whitespace cleanup

    OUTPUT:
    ---------------------------------------------------------
    Returns exact-match accuracy score between:

        0.0 → 1.0

    WHERE:
    ---------------------------------------------------------
    1.0 = all predictions exactly matched
    0.0 = no predictions matched

    WHY THIS METRIC EXISTS:
    ---------------------------------------------------------
    Exact match is:
    - simple
    - interpretable
    - widely used in NLP benchmarks

    HOWEVER:
    ---------------------------------------------------------
    It is NOT semantically robust.

    Two SQL queries may:
    ---------------------------------------------------------
    - look different
    - still produce identical outputs

    So exact match is:
    ---------------------------------------------------------
    syntactic evaluation
    NOT semantic evaluation.
    """



    # =====================================================
    # TRACK CORRECT PREDICTIONS
    # =====================================================

    correct = 0

    # WHY INITIALIZE TO 0:
    # -----------------------------------------------------
    # No correct predictions exist initially.
    #
    # This variable accumulates:
    # -----------------------------------------------------
    # total exact matches.
    #
    # STANDARD COUNTER PATTERN:
    # -----------------------------------------------------
    # initialize
    # increment
    # compute metric
    #
    # WHY NOT 1:
    # -----------------------------------------------------
    # Would incorrectly bias accuracy upward.



    # =====================================================
    # SELECT SUBSET OF TEST DATA
    # =====================================================

    samples = dataset.select(range(num_samples))

    # WHAT THIS DOES:
    # -----------------------------------------------------
    # Extracts limited evaluation subset.
    #
    # WHY LIMIT SAMPLE COUNT:
    # -----------------------------------------------------
    # LLM inference is expensive.
    #
    # Smaller evaluation:
    # -----------------------------------------------------
    # + faster
    # + easier debugging
    # + lower compute cost
    #
    # WHY 20 DEFAULT:
    # -----------------------------------------------------
    # Provides moderate sample size for:
    # - quick benchmarking
    # - visible qualitative inspection
    #
    # TRADE-OFF:
    # -----------------------------------------------------
    # Small sample size:
    # + faster
    # - less statistically reliable
    #
    # LARGE-SCALE BENCHMARKS:
    # -----------------------------------------------------
    # typically evaluate thousands of examples.



    # =====================================================
    # ITERATE THROUGH EVALUATION SAMPLES
    # =====================================================

    for sample in samples:

        # WHY ITERATION:
        # -------------------------------------------------
        # Each sample must be independently:
        # - generated
        # - compared
        # - evaluated
        #
        # THIS IS STANDARD EVALUATION FLOW.
        #
        # TRADE-OFF:
        # -------------------------------------------------
        # Sequential inference:
        # + simpler implementation
        # - slower execution
        #
        # PRODUCTION:
        # -------------------------------------------------
        # Often batched or parallelized.



        # =================================================
        # GENERATE PREDICTED SQL
        # =================================================

        pred_sql = generate_sql(
            sample["sql_prompt"],
            sample["sql_context"]
        )

        # WHAT HAPPENS HERE:
        # -------------------------------------------------
        # Model generates SQL using:
        #
        # - natural language question
        # - database schema
        #
        # PIPELINE:
        # -------------------------------------------------
        # prompt
        #   ↓
        # tokenization
        #   ↓
        # transformer inference
        #   ↓
        # autoregressive decoding
        #   ↓
        # predicted SQL
        #
        # THIS IS THE CORE MODEL INFERENCE STEP.



        # =================================================
        # EXTRACT GROUND-TRUTH SQL
        # =================================================

        gold_sql = sample["sql"]

        # WHAT THIS IS:
        # -------------------------------------------------
        # Human-written correct SQL query.
        #
        # PURPOSE:
        # -------------------------------------------------
        # Acts as benchmark reference answer.
        #
        # IMPORTANT:
        # -------------------------------------------------
        # This is the expected target output.



        # =================================================
        # NORMALIZED EXACT MATCH CHECK
        # =================================================

        if pred_sql.lower().strip() == gold_sql.lower().strip():

            # WHY lower():
            # ---------------------------------------------
            # SQL is mostly case-insensitive.
            #
            # Example:
            # -------------------------------------------------
            # SELECT
            # select
            #
            # should be treated equally.
            #
            # WITHOUT lower():
            # -------------------------------------------------
            # accuracy becomes unfairly lower.
            #
            #
            # WHY strip():
            # ---------------------------------------------
            # Removes:
            # - leading spaces
            # - trailing spaces
            # - extra newlines
            #
            # OTHERWISE:
            # -------------------------------------------------
            # formatting differences falsely reduce accuracy.
            #
            #
            # WHY EXACT STRING COMPARISON:
            # ---------------------------------------------
            # Checks if normalized SQL text is identical.
            #
            # THIS IS:
            # -------------------------------------------------
            # syntactic correctness metric.
            #
            # IMPORTANT LIMITATION:
            # -------------------------------------------------
            # Different SQL queries may still be semantically
            # equivalent.
            #
            # Example:
            #
            # SELECT name FROM users;
            #
            # vs
            #
            # SELECT users.name FROM users;
            #
            # Exact match:
            # -------------------------------------------------
            # FAILS
            #
            # despite identical meaning.



            correct += 1

            # WHY INCREMENT:
            # ---------------------------------------------
            # Tracks successful exact matches.
            #
            # THIS BUILDS FINAL ACCURACY METRIC.
            #
            # TIME COMPLEXITY:
            # -------------------------------------------------
            # String comparison:
            #
            # O(n)
            #
            # where:
            # n = SQL query length



        # =================================================
        # PRINT VISUAL SEPARATOR
        # =================================================

        print("\n====================")

        # WHY THIS EXISTS:
        # -------------------------------------------------
        # Improves console readability.
        #
        # OTHERWISE:
        # -------------------------------------------------
        # outputs become cluttered.
        #
        # IMPORTANT FOR:
        # -------------------------------------------------
        # manual debugging and inspection.



        # =================================================
        # DISPLAY QUESTION
        # =================================================

        print("QUESTION:")
        print(sample["sql_prompt"])

        # WHY PRINT QUESTION:
        # -------------------------------------------------
        # Provides semantic context for evaluation.
        #
        # Helps developers inspect:
        # -------------------------------------------------
        # - reasoning quality
        # - prompt understanding
        # - ambiguity handling



        # =================================================
        # DISPLAY GENERATED SQL
        # =================================================

        print("\nPREDICTED:")
        print(pred_sql)

        # WHY SHOW PREDICTION:
        # -------------------------------------------------
        # Enables qualitative inspection.
        #
        # HUMAN REVIEW CAN DETECT:
        # -------------------------------------------------
        # - hallucinations
        # - malformed SQL
        # - formatting problems
        # - repeated outputs
        #
        # AUTOMATED METRICS ALONE
        # are insufficient in LLM systems.



        # =================================================
        # DISPLAY GROUND-TRUTH SQL
        # =================================================

        print("\nGOLD:")
        print(gold_sql)

        # WHY SHOW GROUND TRUTH:
        # -------------------------------------------------
        # Allows direct side-by-side comparison.
        #
        # Useful for identifying:
        # -------------------------------------------------
        # - syntax differences
        # - missing clauses
        # - incorrect joins
        # - filtering mistakes



    # =====================================================
    # COMPUTE FINAL ACCURACY
    # =====================================================

    accuracy = correct / num_samples

    # WHAT THIS FORMULA REPRESENTS:
    # -----------------------------------------------------
    # Standard classification accuracy:
    #
    # correct_predictions / total_predictions
    #
    # RANGE:
    # -----------------------------------------------------
    # 0.0 → 1.0
    #
    # INTERPRETATION:
    # -----------------------------------------------------
    # 0.75
    #
    # means:
    # 75% exact textual matches.
    #
    # IMPORTANT:
    # -----------------------------------------------------
    # This metric estimates:
    # syntactic alignment
    #
    # NOT semantic correctness.



    # =====================================================
    # DISPLAY FINAL METRIC
    # =====================================================

    print(f"\n✅ Exact Match Accuracy: {accuracy:.2f}")

    # WHY :.2f:
    # -----------------------------------------------------
    # Formats float to 2 decimal places.
    #
    # BENEFITS:
    # -----------------------------------------------------
    # + cleaner logs
    # + easier readability
    #
    # STANDARD METRIC REPORTING PRACTICE.



    # =====================================================
    # RETURN FINAL SCORE
    # =====================================================

    return accuracy

    # WHY RETURN VALUE:
    # -----------------------------------------------------
    # Allows:
    # - experiment tracking
    # - logging
    # - comparisons
    # - hyperparameter tuning
    #
    # PRODUCTION SYSTEMS:
    # -----------------------------------------------------
    # often store metrics in:
    # - MLflow
    # - Weights & Biases
    # - TensorBoard

In [31]:
exact_match_accuracy(dataset["test"], num_samples=5)

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
What is the average explainability score of creative AI applications in 'Europe' and 'North America' in the 'creative_ai' table?

PREDICTED:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

GOLD:
SELECT AVG(explainability_score) FROM creative_ai WHERE region IN ('Europe', 'North America');

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
Delete all records of rural infrastructure projects in Indonesia that have a completion date before 2010.

PREDICTED:
DELETE FROM rural_infrastructure WHERE completion_date < '2010-01-01';

GOLD:
DELETE FROM rural_infrastructure WHERE country = 'Indonesia' AND completion_date < '2010-01-01';

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
How many accidents have been recorded for SpaceX and Blue Origin rocket launches?

PREDICTED:
SELECT COUNT(*) FROM Accidents WHERE launch_provider = 'SpaceX' AND year = 2015;

GOLD:
SELECT launch_provider, COUNT(*) FROM Accidents GROUP BY launch_provider;

Both `max_new_tokens` (=80) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

====================
QUESTION:
What is the maximum quantity of seafood sold in a single transaction?

PREDICTED:
SELECT MAX(quantity) FROM sales;

GOLD:
SELECT MAX(quantity) FROM sales;

====================
QUESTION:
What is the total budget for movies released before 2010?

PREDICTED:
SELECT SUM(budget) FROM Movies_Release_Year WHERE release_year < 2010;

GOLD:
SELECT SUM(budget) FROM Movies_Release_Year WHERE release_year < 2010;

✅ Exact Match Accuracy: 0.60

0.6